### ISSUE TITLE
Use `product_version` to install the version of Chef Infra Client specified, and re-install if a different version of the Client is already installed

### ISSUE THREAD

**Issue by danielcbright** [test-kitchen/test-kitchen#1697] opened 2020-12-01 15:45 UTC
### :speaking_head: Foreword

This FR is to request consistency on how the `product_version` setting is utilized, helping to make TK more user friendly.

Idea: https://chef-software.ideas.aha.io/ideas/SH-I-164

## :frowning_person: Problem Statement

Currently, if you are using an image with Test Kitchen that already has a version of Chef Infra Client installed that is other than the one specified by the `product_version` setting, you must also have `install_strategy` set to `always` in order for the Chef Infra Client to be installed properly. This is not consistent with the behavior that the `chef_client_updater` cookbook uses to update a client or how Chef works in general (non-idempotent.) This makes the user experience more disjointed.

## :grey_question: Possible Solution

If `product_version` was the only setting that needed to be changed to determine if the Chef Infra Client that's already installed on an image needs to be replaced with the specified version, or no action taken due to the versions matching, that would be the solution.

## :arrow_heading_up: Describe alternatives you've considered

One alternative (workaround) used is to specify the `product_name` setting and set it to `chef-workstation`, which installs a version of Chef Workstation that has the version of the Infra Client we want to use, however this is not a long-term solution.

## :heavy_plus_sign: Additional context

I'll let @stevenoneill-jmfamily add more context

**Comment by stevenoneill-jmfamily** [comment] 2020-12-01 16:07
For example, if Chef-Client 14.15.16 is baked in, but latest 16 stable is desired, then I'd expect using provisioner settings of `product_name: chef` and `product_version: 16` to result in a one time update to latest stable 16.  Subsequent runs of test-kitchen would see that latest stable 16 is being used and do no further changes. 

This does not work with the `install_strategy: once".  And with "install_strategy: always" it will re-install, even if it is already at the latest stable.   There does not appear to be an install strategy that would fit.  

As a reference for desired/expected behavior, the chef_client_updater cookbook appears to have the kind of version check and change logic I would expect.  It would be great if that sort of logic is available directly in the TK provisioner.

**Comment by tas50** [comment] 2020-12-09 00:44
I believe this is a duplicate of https://github.com/test-kitchen/test-kitchen/issues/1342

**Closed by tas50** 2020-12-09 00:44 UTC

**Comment by stevenoneill-jmfamily** [comment] 2020-12-09 02:31
Good catch @tas50.  Yes, dupe.

**Comment by tas50** [comment] 2020-12-09 02:34
@danielcbright @stevenoneill-jmfamily Also I REALLY want to get this fixed. It makes testing upgrades hard.
