### ISSUE TITLE
Kitchen destroy fails if VM manually removed

### ISSUE THREAD

**Issue by tfitch** [test-kitchen/test-kitchen#796] opened 2015-07-30 17:33 UTC
Not sure if this is more of a kitchen-vagrant bug.

If you have manually destroyed an image and then try to kitchen destroy, you get an error.

Totally an edge case involving users doing manual intervention on their machines.  But when a machine fails to come up during a `kitchen create|converge|test|verify` command, dropping in to Vagrant or even Virtualbox to remove is what people do to get unstuck.  But then the kitchen status becomes inaccurate and trying to do `kitchen destroy` will throw errors.

If we can account for those errors during the `destroy` that'd be great.

**Comment by puneetloya** [comment] 2015-07-31 17:55
there should be a state_file created in the .kitchen directory (suite-platform.yml). Try deleting it and run kitchen again.

**Comment by tfitch** [comment] 2015-08-03 17:03
Right @puneetloya - that's the existing work around.

What I'm asking for here is the ability for Test Kitchen to just do that itself instead of throwing an error, thus making a better user experience for everyone.

**Comment by tfitch** [comment] 2015-08-03 17:04
Also - this looks identical to https://github.com/test-kitchen/kitchen-vagrant/issues/183 so we can maybe close this as a dupe of that.

**Comment by puneetloya** [comment] 2015-08-03 21:13
@tfitch : I agree as per User experience you might want that. But test-kitchen is more about testing.
So if test-kitchen has not executed properly during a test run, one would try and find the cause of it and clearing kitchen state will actually remove the evidence. Just an opinion :)

**Comment by cheeseplus** [comment] 2016-01-13 20:37
Closing this in favor of https://github.com/test-kitchen/kitchen-vagrant/issues/183

**Closed by cheeseplus** 2016-01-13 20:37 UTC
