### ISSUE TITLE
Busser depends on Ruby (ChefDK) being available on target VM

### ISSUE THREAD

**Issue by lmayorga1980** [test-kitchen/test-kitchen#347] opened 2014-02-05 01:12 UTC
I have a vagrant box with ubuntu precise 64 server with nothing on it. It seems that there are some requirements on the virtual machine in order to get it to work.

```
-----> Starting Kitchen (v1.1.2.dev)
-----> Cleaning up any prior instances of <default-puppet-ubuntu-precise64>
-----> Destroying <default-puppet-ubuntu-precise64>...
       [default] Forcing shutdown of VM...
       [default] Destroying VM and associated drives...
       Vagrant instance <default-puppet-ubuntu-precise64> destroyed.
       Finished destroying <default-puppet-ubuntu-precise64> (0m12.94s).
-----> Testing <default-puppet-ubuntu-precise64>
-----> Creating <default-puppet-ubuntu-precise64>...
       Bringing machine 'default' up with 'virtualbox' provider...
       [default] Importing base box 'ubuntu_master'...
       [default] Matching MAC address for NAT networking...
       [default] Setting the name of the VM...
       [default] Clearing any previously set forwarded ports...
       [default] Clearing any previously set network interfaces...
       [default] Preparing network interfaces based on configuration...
       [default] Forwarding ports...
       [default] -- 22 => 2222 (adapter 1)
       [default] Running 'pre-boot' VM customizations...
       [default] Booting VM...
       [default] Waiting for machine to boot. This may take a few minutes...
       [default] Machine booted and ready!
       [default] Setting hostname...
       Vagrant instance <default-puppet-ubuntu-precise64> created.
       Finished creating <default-puppet-ubuntu-precise64> (0m47.97s).
-----> Converging <default-puppet-ubuntu-precise64>...
       Preparing files for transfer
       Preparing data
       Preparing script
       Transfering files to <default-puppet-ubuntu-precise64>
Reading package lists... Done
Building dependency tree       
Reading state information... 0%
Reading state information... Done
       vim is already the newest version.
       0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
       Finished converging <default-puppet-ubuntu-precise64> (0m3.19s).
-----> Setting up <default-puppet-ubuntu-precise64>...
       sudo: /opt/chef/embedded/bin/gem: command not found
       sudo: /opt/chef/embedded/bin/gem: command not found
sh: 1:        /opt/chef/embedded/bin/ruby: not found
       sudo: /busser: command not found
       sudo: /tmp/busser/bin/busser: command not found
>>>>>> Setup failed on instance <default-puppet-ubuntu-precise64>.
>>>>>> Please see .kitchen/logs/default-puppet-ubuntu-precise64.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c 'BUSSER_ROOT="/tmp/busser" GEM_HOME="/tmp/busser/gems" GEM_PATH="/tmp/busser/gems" GEM_CACHE="/tmp/busser/gems/cache" ; export BUSSER_ROOT GEM_HOME GEM_PATH GEM_CACHE; if ! sudo -E /opt/chef/embedded/bin/gem list busser -i >/dev/null; then sudo -E /opt/chef/embedded/bin/gem install busser --no-rdoc --no-ri; fi; gem_bindir=`/opt/chef/embedded/bin/ruby -rrubygems -e "puts Gem.bindir"`; sudo -E ${gem_bindir}/busser setup; sudo -E /tmp/busser/bin/busser plugin install busser-serverspec']
>>>>>> ----------------------
```

**Comment by kowal** [comment] 2015-02-13 13:58
Hi @lmayorga1980, did you mange to find a way to install Ruby/gems when using shell provisioner?

I've just run into similar problem, however using docker driver. I want to test some bash scripts. I also would expect that test-kitchen knows what is required for given provisioner/driver pair to setup before running tests.

**Comment by mrahtz** [comment] 2015-04-05 15:34
Adding the following to `.kitchen.yml` fixed it for me:
```yaml
busser:
  ruby_bindir: /usr/bin
```

**Comment by cheeseplus** [comment] 2016-02-08 11:51
As stated earlier, Busser requires a working ruby and the `ruby_bindir` key can point to an arbitrary Ruby binary directory. I'm closing this for now as we're already planning on removing any Chef specific hooks in core TK and the issue is germane to busser which now lives as it's own project.

**Closed by cheeseplus** 2016-02-08 11:51 UTC
