### ISSUE TITLE
Kitchen testing for multiple cookbooks

### ISSUE THREAD

**Issue by hanselmahlaola** [test-kitchen/test-kitchen#983] opened 2016-03-31 14:39 UTC
## Description
Currently we have cookbooks and we run kitchen test for each cookbook. We need a way to run Kitchen test for all cookbooks and to only spin up one box and run all tests in all cookbooks against the one box

Running kitchen test on multiple cookbooks

## Kitchen Version

Test Kitchen version 1.6.0

```ruby
# Copy-paste your results here
```

## ChefDK Version

ChefDK 0.12.0

## Ruby Version
ruby -v 2.1.0

## Platform Version

Windows server 2012r2

## Replication Case

create 2 or more cookbooks and run tests on both 

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
# Copy-paste your results here
```

## Kitchen Diagnose

 kitchen diagnose --all                                                                                                                1 ↵
---
timestamp: 2016-03-31 14:43:11 UTC
kitchen_version: 1.6.0
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 0.19.0
      api_version: 2
  provisioner:
    ChefSolo:
      class: Kitchen::Provisioner::ChefSolo
      version: 1.6.0
      api_version: 2
  transport:
    Winrm:
      class: Kitchen::Transport::Winrm
      version: 1.6.0
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.6.0
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config: 
  project_config:
    filename: "/Users/user/projects/absa/windows-go/cookbooks/test/.kitchen.yml"
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_solo
      platforms:
      - name: windows-2012r2
      suites:
      - name: server
        run_list:
        - recipe[dependencies::default]
        attributes: 
  local_config: 
  combined_config:
    filename: 
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_solo
      platforms:
      - name: windows-2012r2
      suites:
      - name: server
        run_list:
        - recipe[dependencies::default]
        attributes: 
instances:
  server-windows-2012r2:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      hostname: 127.0.0.1
      last_action: verify
      password: vagrant
      port: '2204'
      rdp_port: '3389'
      username: vagrant
    driver:
      box: windows-2012r2
      box_check_update: 
      box_url: 
      box_version: 
      customize: {}
      gui: 
      kitchen_root: "/Users/user/projects/absa/windows-go/cookbooks/test"
      log_level: :info
      name: vagrant
      network: []
      pre_create_command: 
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: "/Users/user/projects/absa/windows-go/cookbooks/test/test/integration"
      vagrantfile_erb: "/Users/user/.rvm/gems/ruby-2.1.0/gems/kitchen-vagrant-0.19.0/templates/Vagrantfile.erb"
      vagrantfiles: []
      vm_hostname: 
    provisioner:
      attributes: {}
      chef_omnibus_install_options: 
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_solo_path: "\\bin\\chef-solo.bat"
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path: 
      data_path: 
      encrypted_data_bag_secret_key_path: 
      environments_path: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: "/Users/user/projects/absa/windows-go/cookbooks/test"
      log_file: 
      log_level: :info
      name: chef_solo
      nodes_path: 
      profile_ruby: false
      require_chef_omnibus: true
      roles_path: 
      root_path: "$env:TEMP\\kitchen"
      run_list:
      - recipe[dependencies::default]
      solo_rb: {}
      sudo: 
      sudo_command: 
      test_base_path: "/Users/user/projects/absa/windows-go/cookbooks/test/test/integration"
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: "/Users/user/projects/absa/windows-go/cookbooks/test"
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password: 
      port: 5985
      rdp_port: 3389
      test_base_path: "/Users/user/projects/absa/windows-go/cookbooks/test/test/integration"
      username: administrator
      winrm_transport: :negotiate
    verifier:
      busser_bin: "$env:TEMP\\verifier\\bin\\busser.bat"
      chef_omnibus_root: "/opt/chef"
      command_prefix: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: "/Users/user/projects/absa/windows-go/cookbooks/test"
      log_level: :info
      name: busser
      root_path: "$env:TEMP\\verifier"
      ruby_bindir: "$env:systemdrive\\opscode\\chef\\embedded\\bin"
      sudo: 
      sudo_command: 
      suite_name: server
      test_base_path: "/Users/user/projects/absa/windows-go/cookbooks/test/test/integration"
      version: busser

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment] 2016-04-08 05:10
I'm not sure I understand what is being asked for here exactly.

Do you want test-kitchen to run the tests of all the dependent cookbooks? What exactly does all cookbooks mean?

**Comment by cheeseplus** [comment] 2016-04-08 05:28
Actually, re-reading this is a dupe of #941 which is a dupe of #843 so closing.

**Closed by cheeseplus** 2016-04-08 05:28 UTC
Labels: Feedback Requested
