### ISSUE TITLE
Ability to specify one or many cookbooks path

### ISSUE THREAD

**Issue by bartanxas** [test-kitchen/test-kitchen#1004] opened 2016-04-08 14:46 UTC
## Description

It would be great if we could specify one or more cookbook locations. In current version this feature isn't working:

## Kitchen Version

```ruby
Test Kitchen version 1.7.2
```

## Ruby Version

```ruby
ruby-2.0.0-p643
```

## Platform Version

```ruby
Linux Mint 17.2 Rafaela
```

## Replication Case

```ruby
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "../../data_bags"
  cookbooks_path: "../../cookbooks"

platforms:
- name: centos-6.7
  driver:
    box_url: 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box'
    network:
      - ["public_network", {type: "dhcp", bridge: "eth0"}]
```
```ruby
cookbooks_path:
    - ../cookbooks
    - ../../site-cookbooks
```
```ruby
cookbooks_path: "../../cookbooks"
```
## Kitchen Output

```ruby
     Transferring files to <default-centos-67>
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/validation.pem (1679 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/client.rb (617 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/data_bags/property_service/gitlab.json (642 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/data_bags/property_service/version_one.json (878 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/data_bags/zabbix_server_bag/zabbix_server_item.json (208 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/data_bags/keystore/keystore_password.json (210 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/data_bags/zabbix_bag/zabbix_item.json (223 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/dna.json (349 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/README.md (1563 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/attributes/default.rb (2608 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/metadata.rb (388 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/templates/default/nginx.conf.erb (297 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/templates/default/gunicorn_config.py.erb (588 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/templates/default/config.conf.erb (362 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/recipes/deploy.rb (2593 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/recipes/default.rb (42 bytes)
D      Uploaded /tmp/default-centos-67-sandbox-20160408-21601-6u5jh6/cookbooks/property_service/recipes/users.rb (169 bytes)
D      Transfer complete
D      [SSH] vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/home/evo
lkov/Projects/repos/chef_kitchen/cookbooks/property_service/.kitchen/kitchen-vagrant/kitchen-property_service-default-centos-67/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :user=>"vagrant"}> (sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
')
       Starting Chef Client, version 12.8.1
       resolving cookbooks for run list: ["property_service::default"]
       
       =============================================================================

       
       ================================================================================
       Error Resolving Cookbooks for Run List:
       ================================================================================
       
       Missing Cookbooks:
       ------------------
       No such cookbook: application_git
       
       Expanded Run List:
       ------------------
       * property_service::default

```

## Kitchen Diagnose
```ruby
timestamp: '2016-04-08 14:43:53 UTC'
kitchen_version: 1.7.2
instances:
  default-centos-67:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: create
      port: '2222'
      ssh_key: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service/.kitchen/kitchen-vagrant/kitchen-property_service-default-centos-67/.vagrant/machines/default/virtualbox/private_key
      username: vagrant
    driver:
      boot_timeout: 
      box: bento/centos-6.7
      box_check_update: 
      box_download_insecure: 
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box
      box_version: 
      customize: {}
      gui: 
      kitchen_root: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service
      linked_clone: 
      log_level: :info
      name: vagrant
      network:
      - - public_network
        - type: dhcp
          bridge: eth0
      pre_create_command: 
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders: []
      test_base_path: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service/test/integration
      vagrant_binary: vagrant
      vagrantfile_erb: /home/user/.rvm/gems/ruby-2.0.0-p643/gems/kitchen-vagrant-0.20.0/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: default-centos-67
    provisioner:
      attributes:
        property_service:
          home: /opt/property_service
          python_ver: '2.7'
          repository: http://some_repository/microservices.git
          revision: propservice
          django_db: sqlite:///property_service.db
          django_db_migrate: true
          address: 127.0.0.1:9001
          nginx_port: '9000'
          use_proxy: true
      chef_client_path: /bin/chef-client
      chef_omnibus_install_options: 
      chef_omnibus_url: https://www.chef.io/chef/install.sh
chef_zero_host: 
      chef_zero_port: 8889
      client_rb: {}
      clients_path: 
      command_prefix: 
      config_path: 
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      cookbooks_path: ../../cookbooks
      data_bags_path: /home/user/Projects/repos/chef_kitchen/data_bags
      data_path: 
      encrypted_data_bag_secret_key_path: 
      environments_path: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      json_attributes: true
      kitchen_root: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service
      log_file: 
      log_level: auto
      name: chef_zero
      nodes_path: 
      profile_ruby: false
      require_chef_omnibus: true
      roles_path: 
      root_path: /tmp/kitchen
      ruby_bindir: /embedded/bin
      run_list:
      - recipe[property_service::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service/test/integration
    transport:
      compression: true
      compression_level: 6
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service
      log_level: :info
      mevolkovait_until_ready: 600
      name: ssh
      port: 22
      ssh_key: 
      test_base_path: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service/test/integration
      username: root
    verifier:
      busser_bin: /tmp/verifier/bin/busser
      chef_omnibus_root: /opt/chef
      evolkovand_prefix: 
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service
      log_level: :info
      name: busser
      root_path: /tmp/verifier
      ruby_bindir: /opt/chef/embedded/binevolkov   sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: /home/user/Projects/repos/chef_kitchen/cookbooks/property_service/test/integration
      version: busser
```

**Comment by cheeseplus** [comment] 2016-04-08 17:25
Closing this as a dupe of https://github.com/test-kitchen/test-kitchen/pull/393 where we are currently tracking that work - we may re-open an issue for the feature but we don't really need all the debug output for that ;)

**Closed by cheeseplus** 2016-04-08 17:25 UTC
