### ISSUE TITLE
Chef::Log.warn never print out

### ISSUE THREAD

**Issue by chrisduong** [test-kitchen/test-kitchen#694] opened 2015-04-17 08:28 UTC
Hi,

Please let me have a silly question.
I'm writing a recipe, and I want to print out some messages on terminal during Chef run.
Even though i export KITCHEN_LOG='INFO', the message still not shown up.

```ruby
Chef::Log.warn("never print out")
Chef::Log.info("never print out")
```

The only way I can do is to use `puts` method.
Thanks for reading

**Comment by daxgames** [comment] 2015-04-21 13:49
I have seen this as well.  The Chef::Log.error alway shows though.

**Comment by mconigliaro** [comment] 2015-05-08 21:54
Same problem here on 1.4.0 with ChefDK 0.5.1.

**Comment by jkleinlercher** [comment] 2015-05-11 06:28
I have the same problem - any ideas?

**Comment by LevonBecker** [comment] 2015-05-12 20:54
I kind of have the same issue. I can't get Log.info to output even with -l info argument.  Debug is a nightmare to filter through. 

The one different is I can get Log.warn to show without giving a log level.

Chef::Log.warn('################################################')   [Works]

When I give it the -l debug such as ```kitchen converge suitename -l debug``` I only get Debug messages... no WARN or INFO.

I also tried this .kitchen.yml setting for the chef_client and it didn't change anything.
https://docs.chef.io/config_yml_kitchen.html 

I'm using Chef_Zero latest client 12.3.x

**Comment by s-bernard** [comment] 2015-06-03 17:20
I guess I have the same problem. Chef::Log.info is not printed in -l info, only in debug. Warn and error are printed in info but not in warn or error. Debug is OK.

**Comment by zoran** [comment] 2016-02-23 16:44
same here

**Comment by matthew-churcher** [comment] 2016-03-22 18:59
:-(

**Comment by cheeseplus** [comment] 2016-03-22 19:03
Hey folks, this is a dupe of https://github.com/test-kitchen/test-kitchen/issues/694 and I'm closing it so we can keep it focused on one issue.

There is also a PR, #950, that addresses this.

**Closed by cheeseplus** 2016-03-22 19:03 UTC

**Comment by scottymarshall** [comment] 2016-03-22 19:11
This is #694.  Did you mean a different one?

**Comment by cheeseplus** [comment] 2016-03-22 19:16
Edited for https://github.com/test-kitchen/test-kitchen/issues/529
