### ISSUE TITLE
Zip Transport fails on Windows Server Core

### ISSUE THREAD

**Issue by blairham** [test-kitchen/test-kitchen#625] opened 2015-03-02 15:29 UTC
Windows Core does not have zip shell extensions, thus breaking transport. I had reverted the zip file changes locally and have verified that things do work again.

http://serverfault.com/questions/446884/unzip-file-with-powershell-in-server-2012-core

**Comment by fnichol** [comment] 2015-03-20 16:59
Hi there!

Agreed, I've been able to repro this issue now that I have a relevant Windows Server 2012r2 Standard/Core VM to run against. I'm looking into this today and will update with comments and/or fix :smile:

**Comment by fnichol** [comment] 2015-03-21 17:21
@blairham I can confirm what you are seeing and looking for a reasonable solution which (I'm hoping) doesn't involve installing .NET 4.5 on demand for this version of Windows Server. I have a checklist going in #640 to keep track of which versions of Windows have been tested and which are pending.

I'll update this issue again with updates. Thanks!

**Comment by fnichol** [comment] 2015-03-23 21:09
@blairham, I'm hoping we've resolved this as of a35ccc565f7a3e7dde707843c389fdbd020ccd99 which involved using `[System.IO.Compression.ZipFile]::ExtractToDirectory("$src", "$dst")` but only if .NET 4.5 was present on the system (the fallback behavior is as before).

I'm going to close this out--if you see different results, please reopen or file a new issue. Thanks!

**Closed** 2015-03-23 21:10 UTC
Labels: in progress, Windows

**Comment by Annih** [comment] 2015-06-20 09:44
Hello @fnichol,

I have the same issue but with Windows Server 2008R2 Core, I check your check list in #640, and there is no mention of this Windows version :(
Would it be possible to fallback to the embedded `tar` binary when nothing worked?

I know this is not the best solution to rely on binaries Embedded with the chef omnibus install, but at least there is still a way to easily unzip the cookbooks :)

Regards!

**Comment by xmik** [comment] 2015-06-20 10:22
@Annih, could you try winrm-transport branch: [fix_com_unpacking](https://github.com/test-kitchen/winrm-transport/tree/smurawski/fix_com_unpacking)? It solved for me the problem that cookbooks were uploaded to windows guest machine, but were not unzipped.  

There is another related thread: https://github.com/test-kitchen/winrm-transport/pull/9.

**Comment by Annih** [comment] 2015-06-20 10:37
Thanks for your help @xmik , but I already tried this branch without success.
It still fails when calling the `shell.NameSpace` method:
> Exception calling "NameSpace" with "1" argument(s): "Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))"

This is due to the same reason that @fnichol fallback to the .NET 4.5 `System.IO.Compression` class on 2012R2 core: Windows Server Core does not ship with the zip module

I also created an issue for that [test-kitchen/winrm-transport#11](https://github.com/test-kitchen/winrm-transport/issues/11)
