### ISSUE TITLE
Instance Gets Prematurely Destroyed Before Verification

### ISSUE THREAD

**Issue by paulcalabro** [test-kitchen/test-kitchen#1468] opened 2018-09-25 05:38 UTC
## Description

Running `kitchen test` with multiple platforms, one for Windows and one for Ubuntu, results in the successful completion of all life cycle events  **except for testing** for the first instance (Ubuntu), and the successful completion of all life cycle events with no issues for the second instance (Windows). 

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.23.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
N/A
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
```

## Platform Version

- Ubuntu 16.04
- WINDOWS 2012 R2

## Replication Case

`kitchen test`

## Kitchen Output

After a successful: destroy, create, and converge...but _no verify_.
```
[21:13:20]Playbook run took 0 days, 0 hours, 6 minutes, 54 seconds
[21:13:20]       *************** AnsiblePush end run *******************
[21:13:20]-----> Destroying <default-ubuntu-1604>...
[21:13:20]-----> Cleaning up any prior instances of <default-windows-2012r2>
[21:13:20]-----> Destroying <default-windows-2012r2>...
[21:13:20]       Finished destroying <default-windows-2012r2> (0m0.00s).
[21:13:20]-----> Testing <default-windows-2012r2>
[21:13:20]-----> Creating <default-windows-2012r2>...
[21:13:21]       Detected platform: windows version 8rtm on x86_64. Instance Type: m5.large. Default username: administrator (default).
[21:13:21]       If you are not using an account that qualifies under the AWS
```

The second instance (Windows), however, has no issues running the tests:

```
[21:44:02]Playbook run took 0 days, 0 hours, 23 minutes, 54 seconds
[21:44:02]       *************** AnsiblePush end run *******************
[21:44:14]       True
[21:44:14]       Downloading files from <default-windows-2012r2>
[21:44:14]       Finished converging <default-windows-2012r2> (24m21.02s).
[21:44:14]-----> Setting up <default-windows-2012r2>...
[21:44:14]       Finished setting up <default-windows-2012r2> (0m0.00s).
[21:44:14]-----> Verifying <default-windows-2012r2>...
[21:44:14]       Detected alternative framework tests for `inspec`
[21:44:16]       Loaded common 
```

## Kitchen Diagnose

https://gist.github.com/paulcalabro/9c3199dbeef5e04c2e3b2a43411f25d7

## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by cheeseplus** [comment] 2018-09-26 14:42
Nothing inherently wrong with Ruby 2.3 that I know of, just the only thing that stands out. It'd also be useful to know what the `test` folder looks like as per `tree` (or equivalent). It's possible this is something the provisioner (ansible) is doing too but this setup is not exactly a simple repro.

**Comment by marcparadise** [comment] 2021-04-14 17:40
There's been no additional response since 2018; @paulcalabro - I'm going to close this out, but if the issue is still occurring/relevant please re-open it and provide the additional requested info.

**Closed by marcparadise** 2021-04-14 17:40 UTC
