### ISSUE TITLE
Omnibus script hangs if it can't get perms on /tmp/stderr 

### ISSUE THREAD

**Issue by glasschef** [test-kitchen/test-kitchen#744] opened 2015-06-12 17:55 UTC
https://github.com/test-kitchen/test-kitchen/blob/master/support/chef_base_install_command.sh

If /tmp/stderr is created initially by root, for example, and later another user tries the omnibus install, wget will try to output errors since install.sh exists (owned by root) but the actual /tmp/stderr file is owned by root as well, so it just hangs:

```
Trying wget...

sh: line 140: /tmp/stderr: Permission denied

...
```

**Comment by pmoosh** [comment] 2015-06-20 02:56
Seen this on Red Hat Enterprise Linux Server release 6.5 and chefDK 0.6.2

**Comment by phasebash** [comment] 2015-08-21 15:32
I am experiencing this problem as well.  How can one work around and/or fix this?

**Comment by joshwand** [comment] 2015-10-21 23:28
+1

**Comment by mgolfieri** [comment] 2015-12-04 22:41
+1

**Comment by jamandbees** [comment] 2015-12-16 17:50
+1

I'm using test-kitchen version 1.4.0. I see this error consistently if I change the version of the chef-omnibus package being installed with chef-solo with a CentOS 6.4 virtual machine as the vagrant base box being used. All I need to do to reproduce is add:

    provisioner:
      name: chef_solo
      require_chef_omnibus: 11.10.4

to my .kitchen.yml and  try to run a test. So far, it's reproducible with any arbitrary version of the chef omnibus.

**Comment by cheeseplus** [comment] 2016-02-08 17:28
Cant' say I've ever seen this one but will try to repro - does this occur with Chef 12+ builds as well?

**Comment by mgolfieri** [comment] 2016-02-08 19:44
Yes, it's happening with any chef version 11 and above.

**Comment by cheeseplus** [comment] 2017-09-13 05:04
Been unable to reproduce this one for 2 years, closing this out but happy to field a new issue opened with a repro steps against a current chef version.

**Closed by cheeseplus** 2017-09-13 05:04 UTC
Labels: Accepted, Bug, Provisioner: Chef
