### ISSUE TITLE
second converge fails with encrypted data bags

### ISSUE THREAD

**Issue by eheydrick** [test-kitchen/test-kitchen#611] opened 2015-02-11 21:20 UTC
With encrypted_data_bag_secret_key_path set in kitchen.yml the first converge succeeds but the second one fails with a permissions problem:

```
$ kitchen verify
-----> Starting Kitchen (v1.3.1)
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ubuntu-1404>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [scp: /tmp/kitchen/encrypted_data_bag_secret: Permission denied
]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
The problem is the mode of /tmp/kitchen/encrypted_data_bag_secret is set to 400 and it should be 600 so it's writable.

**Comment by fnichol** [comment] 2015-02-11 22:05
Could you check the permissions of your `encrypted_data_bag_secret` file on your local workstation? The files are transferred with SCP and maintain the permissions by default. While these permissions might not be ideal in production, you should be okay with 0600 for testing purposes. Was this intentional?

Would you be able to provide the output of the first run succeeding, maybe with the `-l debug` flag? Thanks!

**Comment by eheydrick** [comment] 2015-02-11 22:52
It is indeed 400 on my workstation. If I set to 600 I can converge more than once. Should we chmod it inside the kitchen instance?

**Comment by tyler-ball** [comment] 2015-02-13 21:24
https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L93-L99

The issue is that we are not clearing out the directory the encrypted data bag secret is written to when copying over the sandbox directory.  We'll put this bug in our backlog to fix when we get a chance.

We also need to remember to port whatever fix we do to the windows-guest-support branch, where shells are responsible for `init_command`.

**Comment by fnichol** [comment] 2015-03-29 20:14
Hi @eheydrick, I think we have this covered in #673. It'll ship in the next gem release. Thanks for your feedback diagnosing this issue!

**Closed** 2015-03-29 20:13 UTC
Labels: Bug
