### ISSUE TITLE
Ability to specify an array of data bag locations

### ISSUE THREAD

**Issue by dansteen** [test-kitchen/test-kitchen#482] opened 2014-07-29 22:42 UTC
It would be great if we could specify an array of locations to look for databags.   This would allow us to store databags with the cookbook that they are part of, while still pulling in databags from other cookbooks that are used as well.   

Thanks!

**Comment by iiro** [comment] 2015-04-14 19:37
Sorry to use this issue but it would be really useful to have this for roles path as well...

**Comment by EugenMayer** [comment] 2016-12-02 10:47
Thats a dupe of #634 isnt it? (or the other way arround) - seems like #634 has been worked on, so this one should probably be closed @cheeseplus

**Comment by cheeseplus** [comment] 2018-04-16 22:43
Closed by #1313

**Closed by cheeseplus** 2018-04-16 22:43 UTC
Labels: Improvement, Provisioner: Chef
