### ISSUE TITLE
test-kitchen 1.5 has different chef_client_path

### ISSUE THREAD

**Issue by thompsm** [test-kitchen/test-kitchen#968] opened 2016-03-11 14:18 UTC
## Description

This issues causes a converge to fail on a RHEL6 EC2 instance.

Running version 1.4.2 of test-kitchen, kitchen diagnose said chef_client_path was:

```
/opt/chef/bin/chef-client
```

I've just installed chefdk 0.11.2, which uses 1.5.0 of test-kitchen, and now chef_client_path is:

```
/bin/chef-client
```

I can add this to my .kitchen/config.yml to workaround the problem:

```
provisioner:
  name: chef_zero
  chef_client_path: '/opt/bin/chef-chef-client'
```

## Kitchen Version

Test Kitchen version 1.5.0

## ChefDK Version

```
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
```

## Platform Version

```
Mac OSX
```

## Replication Case

Converge now fails as it can't find the chef-client:

```
kitchen converge default-aws-nonprod-rhel6
-----> Starting Kitchen (v1.5.0)
-----> Converging <default-aws-nonprod-rhel6>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.2.1...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing environments
       Preparing roles
       Preparing validation.pem
       Preparing client.rb
       Transferring files to <default-aws-nonprod-rhel6>
       sudo: /bin/chef-client: command not found
>>>>>> Converge failed on instance <default-aws-nonprod-rhel6>.
>>>>>> Please see .kitchen/logs/default-aws-nonprod-rhel6.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
[ Proxy info cut from here ]
sudo -E /bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level warn --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------
zlib(finalizer): the stream was freed prematurely.
```

## Kitchen Log

```
I, [2016-03-11T14:03:46.296578 #8300]  INFO -- default-aws-nonprod-rhel6: -----> Converging <default-aws-nonprod-rhel6>...
I, [2016-03-11T14:03:46.297076 #8300]  INFO -- default-aws-nonprod-rhel6: Preparing files for transfer
I, [2016-03-11T14:03:46.297147 #8300]  INFO -- default-aws-nonprod-rhel6: Preparing dna.json
I, [2016-03-11T14:03:46.297870 #8300]  INFO -- default-aws-nonprod-rhel6: Resolving cookbook dependencies with Berkshelf 4.2.1...
I, [2016-03-11T14:03:46.467809 #8300]  INFO -- default-aws-nonprod-rhel6: Removing non-cookbook files before transfer
I, [2016-03-11T14:03:46.472606 #8300]  INFO -- default-aws-nonprod-rhel6: Preparing data_bags
I, [2016-03-11T14:03:46.472801 #8300]  INFO -- default-aws-nonprod-rhel6: Preparing environments
I, [2016-03-11T14:03:46.474563 #8300]  INFO -- default-aws-nonprod-rhel6: Preparing roles
I, [2016-03-11T14:03:46.474808 #8300]  INFO -- default-aws-nonprod-rhel6: Preparing validation.pem
I, [2016-03-11T14:03:46.475320 #8300]  INFO -- default-aws-nonprod-rhel6: Preparing client.rb
I, [2016-03-11T14:03:46.900510 #8300]  INFO -- default-aws-nonprod-rhel6: Transferring files to <default-aws-nonprod-rhel6>
I, [2016-03-11T14:03:50.805318 #8300]  INFO -- default-aws-nonprod-rhel6: sudo: /bin/chef-client: command not found
E, [2016-03-11T14:03:50.811432 #8300] ERROR -- default-aws-nonprod-rhel6: Converge failed on instance <default-aws-nonprod-rhel6>.
E, [2016-03-11T14:03:50.811538 #8300] ERROR -- default-aws-nonprod-rhel6: ------Exception-------
E, [2016-03-11T14:03:50.811565 #8300] ERROR -- default-aws-nonprod-rhel6: Class: Kitchen::ActionFailed
```

**Comment by cheeseplus** [comment] 2016-03-11 15:00
@thompsm so chef_client_path is referring to the chef-client inside the VM itself, not on your host system.

**Comment by thompsm** [comment] 2016-03-11 16:16
Yes I do have the chef-client pre-installed in the AMI I'm using. This wasn't a problem with 1.4.2 of test-kitchen though.

**Comment by cheeseplus** [comment] 2016-03-11 16:23
So what I'm unclear on is whether the end node has ChefDK installed or not? TK shouldn't be doing anything special here.

**Comment by cheeseplus** [comment] 2016-03-11 16:26
Ah, looks like this is a dupe of https://github.com/test-kitchen/test-kitchen/issues/923

**Comment by thompsm** [comment] 2016-03-11 16:46
Yes the end node has the Chef client RPM pre-installed.

Agreed it's the same as 923.

**Comment by cheeseplus** [comment] 2016-03-11 18:54
Closing as dupe but feel free to participate on the existing issue.

**Closed by cheeseplus** 2016-03-11 18:54 UTC
Labels: Duplicate, Question, Triaged
