### ISSUE TITLE
Idea: new driver for footloose

### ISSUE THREAD

**Issue by ehaselwanter** [test-kitchen/test-kitchen#1594] opened 2019-09-24 13:25 UTC
just putting an idea here: came across an interesting project for a new kitchen driver: https://www.weave.works/blog/an-introduction-to-footloose-containers-that-look-like-vms

**Comment by lamont-granquist** [comment] 2019-10-11 01:41
This isn't a bad idea, but since its not a bug or feature directly in test-kitchen I'm going to have to close this.

**Closed by lamont-granquist** 2019-10-11 01:41 UTC
