### ISSUE TITLE
Intermittent "No such file or directory" on Windows converge

### ISSUE THREAD

**Issue by stonith** [test-kitchen/test-kitchen#699] opened 2015-04-18 08:40 UTC
Using Windows host/guest with ChefDK 0.50rc5. Sometimes `kitchen converge` works without issue however, sometimes it fails with:

```
role_windows_2012_packer [ development ] > kitchen converge
-----> Starting Kitchen (v1.4.0.rc.1)
-----> Converging <default-windows-2012R2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [No such file or directory @ rb_sysopen - C:/Users/me/AppData/Local/Temp/default-windows-2012R2-sandbox-20150417-5436-1o2yzac/cookbooks/role_windows_2012_packer/.kitchen/kitchen-vagrant/kitchen-role_windows_2012_packer-default-windows-2012R2/.vagrant/machines/default/virtualbox/action_set_name]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

The kitchen.log is here: https://gist.github.com/stonith/688ed3384c80b0e7b89a

This seems to happen intermittently. Sometimes trying `kitchen converge` again works but often it doesn't.

**Comment by stonith** [comment] 2015-04-19 17:06
This may be a timing issue where berks is expecting the `C:\users\me\AppData\Local\Temp\<kitchensuite>\` folder to be created but sometimes it's not yet when it's looking.

**Comment by stonith** [comment] 2015-04-19 17:47
I tried running `kitchen converge -l debug` and the following is a successful converge:

```
role_windows_2012_packer [ development ] > kitchen converge -l debug
-----> Starting Kitchen (v1.4.0.rc.1)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      [Vagrant command] BEGIN (vagrant plugin list)
D      [Vagrant command] END (0m0.00s)
D      Berksfile found at E:/chefrepo/vci-cookbooks/role_windows_2012_packer/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 library loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.0 library loaded
-----> Converging <default-windows-2012R2>...
       Preparing files for transfer
D      Creating local sandbox in C:/Users/me/AppData/Local/Temp/default-windows-2012R2-sandbox-20150419-4276-1nnt8j
       Preparing dna.json
D      Creating dna.json from {:global=>{:chef=>{:media=>"mediaserver.int.local"}}, :run_list=>["recipe[role_windows_2012_packer::default]"]}
       Resolving cookbook dependencies with Berkshelf 3.2.3...
D      Using Berksfile from E:/chefrepo/vci-cookbooks/role_windows_2012_packer/Berksfile
       Removing non-cookbook files before transfer
       Preparing data_bags
D      Using data_bags from E:/chefrepo/vci-cookbooks/role_windows_2012_packer/test/integration/default/data_bags
       Preparing environments
D      Using environments from E:/chefrepo/vci-cookbooks/role_windows_2012_packer/test/environments
       Preparing validation.pem
D      Using a dummy validation.pem
       Preparing client.rb
```

And the following is the beginning of when it throws the error:
```
role_windows_2012_packer [ development ] > kitchen converge -l debug
-----> Starting Kitchen (v1.4.0.rc.1)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      [Vagrant command] BEGIN (vagrant plugin list)
D      [Vagrant command] END (0m0.00s)
D      Berksfile found at E:/chefrepo/vci-cookbooks/role_windows_2012_packer/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 library loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.0 library loaded
-----> Converging <default-windows-2012R2>...
       Preparing files for transfer
D      Creating local sandbox in C:/Users/me/AppData/Local/Temp/default-windows-2012R2-sandbox-20150419-7608-1eqk9sb
       Preparing dna.json
D      Creating dna.json from {:global=>{:chef=>{:media=>"mediaserver.int.local"}}, :run_list=>["recipe[role_windows_2012_packer::default]"]}
       Resolving cookbook dependencies with Berkshelf 3.2.3...
D      Using Berksfile from E:/chefrepo/vci-cookbooks/role_windows_2012_packer/Berksfile
D      Cleaning up local sandbox in C:/Users/me/AppData/Local/Temp/default-windows-2012R2-sandbox-20150419-7608-1eqk9sb
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [No such file or directory @ rb_sysopen - C:/Users/me/AppData/Local/Temp/default-windows-2012R2-san
dbox-20150419-7608-1eqk9sb/cookbooks/role_windows_2012_packer/.kitchen/kitchen-vagrant/kitchen-role_windows_2012_packer-default-windows-2012R2/.vagrant/machines
/default/virtualbox/action_set_name]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #converge action: [No such file or directory @ rb_sysopen - C:/Users/me/AppData/Local/Temp/default-windows-2012R2-san
dbox-20150419-7608-1eqk9sb/cookbooks/role_windows_2012_packer/.kitchen/kitchen-vagrant/kitchen-role_windows_2012_packer-default-windows-2012R2/.vagrant/machines
/default/virtualbox/action_set_name]
D      ---Nested Exception---
D      Class: Errno::ENOENT
D      Message: No such file or directory @ rb_sysopen - C:/Users/me/AppData/Local/Temp/default-windows-2012R2-sandbox-20150419-7608-1eqk9sb/cookbooks/r
ole_windows_2012_packer/.kitchen/kitchen-vagrant/kitchen-role_windows_2012_packer-default-windows-2012R2/.vagrant/machines/default/virtualbox/action_set_name
```

Successful converge logs `Removing non-cookbook files before transfer` after `Using Berksfile from...` but error converge logs `Cleaning up local sandbox in C:/Users/me/AppData/Local/Temp/default-windows-2012R2-sandbox-20150419-7608-1eqk9sb` instead.

**Comment by stonith** [comment] 2015-04-20 00:30
I also can't seem to reproduce this with OSX as the host instead of Windows.

**Comment by stonith** [comment] 2015-04-20 06:06
Closing this for now as I'm pretty certain I'm hitting the [Windows maximum path length limit.](https://msdn.microsoft.com/en-us/library/aa365247.aspx)

**Comment by stonith** [comment] 2015-04-20 17:14
I'm reopening this as it's not that difficult to run into this limit on Windows hosts and my colleague wasted hours on this. At a minimum, might I suggest a warning to the effect of the Windows path limit?

**Comment by tyler-ball** [comment] 2015-05-11 21:38
Hey @stonith - it looks like its failing when Berkshelf is resolving the dependencies.  Can you try updating (or adding if it doesn't exist) your [.chefignore](https://docs.chef.io/chef_repo.html#chefignore-files) file to ignore `./.kitchen`?  I think an entry like `*/.kitchen/*` should work.

Berkshelf will respect the `.chefignore` file and won't try to look into that directory, meaning it won't run into the long path limits (hopefully).

**Comment by monkey1016** [comment] 2015-05-14 13:06
@tyler-ball Thanks.  I recently ran into this issue and adding `.kitchen` to `chefignore` resolved the issue for me.

**Comment by valerie-roske** [comment] 2015-05-17 01:23
@tyler-ball I continue to get this error after adding a `.chefignore` file.

**Comment by tyler-ball** [comment] 2015-05-18 18:35
@valerie-roske are you using the latest version of the ChefDK?

**Comment by valerie-roske** [comment] 2015-05-19 03:55
@tyler-ball Yes, I'm using the latest version of ChefDK, and it's still trying to look into the sandbox directory. Any thoughts on this?

**Comment by tyler-ball** [comment] 2015-05-20 21:58
@valerie-roske can you give the output of you `.kitchen/logs/kitchen.log` file when running into this error and the output of your `kitchen diagnose`?  And you're experiencing this on a Windows host, yes?

**Comment by valerie-roske** [comment] 2015-06-01 04:59
@tyler-ball yep, on Windows 7!

#### `$ cat .kitchen/logs/kitchen.log`

I, [2015-05-31T22:26:20.102100 #7264]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.0)
I, [2015-05-31T22:26:22.564120 #7264]  INFO -- Kitchen: -----> Converging <microwave-rails-chef-microwave-rails-box>...
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: ------Exception-------
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: Message: Failed to complete #converge action: [No such file or directory @ dir_s_mkdir - C:/Users/Valerie/AppData/Local/Temp
/microwave-rails-chef-microwave-rails-box-sandbox-20150531-7264-1tg27em/cookbooks/microwave-rails-chef/.kitchen/kitchen-vagrant/kitchen-cookbook-microwave-rails-chef-microwave-rail
s-box/.vagrant/machines/default/virtualbox]
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: ---Nested Exception---
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: Class: Errno::ENOENT
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: Message: No such file or directory @ dir_s_mkdir - C:/Users/Valerie/AppData/Local/Temp/microwave-rails-chef-microwave-rails-
box-sandbox-20150531-7264-1tg27em/cookbooks/microwave-rails-chef/.kitchen/kitchen-vagrant/kitchen-cookbook-microwave-rails-chef-microwave-rails-box/.vagrant/machines/default/virtua
lbox
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: ------Backtrace-------
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:208:in `each'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/file_syncer.rb:80:in `block in sync'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/file_syncer.rb:71:in `each'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/file_syncer.rb:71:in `sync'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/berksfile.rb:624:in `block in vendor'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/berksfile.rb:581:in `vendor'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/berkshelf.rb:68:in `block in resolve'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/shell/basic.rb:20:in `mute'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/berkshelf.rb:64:in `resolve'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/common_sandbox.rb:286:in `block in resolve_with_be
rkshelf'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/common_sandbox.rb:285:in `synchronize'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/common_sandbox.rb:285:in `resolve_with_berkshelf'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/common_sandbox.rb:251:in `prepare_cookbooks'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef/common_sandbox.rb:50:in `populate'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef_base.rb:99:in `create_sandbox'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/chef_solo.rb:44:in `create_sandbox'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/base.rb:61:in `call'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:366:in `block in converge_action'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:488:in `call'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:452:in `action'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:362:in `converge_action'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `each'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:138:in `converge'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: c:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-05-31T22:26:27.361629 #7264] ERROR -- Kitchen: ----------------------

#### `$ kitchen diagnose`

timestamp: 2015-06-01 04:55:45 UTC
kitchen_version: 1.4.0
instances:
  microwave-rails-chef-microwave-rails-box:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      hostname: 127.0.0.1
      last_action: create
      port: '2222'
      ssh_key: C:/Users/Valerie/.vagrant.d/insecure_private_key
      username: vagrant
    driver:
      box: ubuntu/trusty64
      box_check_update:
      box_url:
      box_version:
      customize: {}
      gui:
      kitchen_root: c:/Users/Valerie/Desktop/microwave-rails/cookbook
      log_level: :info
      name: vagrant
      network:
      - - forwarded_port
        - guest: 3000
          host: 4001
      - - forwarded_port
        - guest: 9292
          host: 5001
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders:
      - - c:/Users/Valerie/Desktop/microwave-rails/rails-app
        - "/home/vagrant/microwave-workspace"
        - nil
      test_base_path: c:/Users/Valerie/Desktop/microwave-rails/cookbook/test/integration
      vagrantfile_erb: c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: microwave-rails-chef-microwave-rails-box
    provisioner:
      attributes: {}
      chef_metadata_url:
      chef_omnibus_install_options:
      chef_omnibus_root: "/opt/chef"
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_solo_path: "/opt/chef/bin/chef-solo"
      clients_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      http_proxy:
      https_proxy:
      kitchen_root: c:/Users/Valerie/Desktop/microwave-rails/cookbook
      log_file:
      log_level: :info
      name: chef_solo
      nodes_path:
      require_chef_omnibus: true
      roles_path:
      root_path: "/tmp/kitchen"
      run_list:
      - microwave-rails-chef
      solo_rb: {}
      sudo: true
      sudo_command: sudo -E
      test_base_path: c:/Users/Valerie/Desktop/microwave-rails/cookbook/test/integration
    transport:
      compression: zlib
      compression_level: 6
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: c:/Users/Valerie/Desktop/microwave-rails/cookbook
      log_level: :info
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_key:
      test_base_path: c:/Users/Valerie/Desktop/microwave-rails/cookbook/test/integration
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      http_proxy:
      https_proxy:
      kitchen_root: c:/Users/Valerie/Desktop/microwave-rails/cookbook
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: microwave-rails-chef
      test_base_path: c:/Users/Valerie/Desktop/microwave-rails/cookbook/test/integration
      version: busser

**Comment by tyler-ball** [comment] 2015-06-02 18:03
@valerie-roske Sorry to keep asking for more information, but I'm still perplexed - can you include the contents of `c:/Users/Valerie/Desktop/microwave-rails/cookbook/.chefignore` here as well?

**Comment by tyler-ball** [comment] 2015-06-02 23:32
Also, I was totally wrong - the file is just `chefignore` at the root of the cookbook, without the leading `.` :disappointed:

**Comment by zl4bv** [comment] 2015-06-03 02:56
Seeing this issue too from a Windows Server 2008 R2 host. ChefDK 0.6.0.

Strangely, Berkshelf seems to be ignoring my `chefignore` file.

chefignore, stacktrace, & `kitchen diagnose` output: https://gist.github.com/zl4bv/dc72e2b49ba54889da2c

**Comment by zl4bv** [comment] 2015-06-03 03:51
By the looks of chef/chef-dk#386 the entries in chefignore should look like `.kitchen` instead of `*/.kitchen/*`

**Comment by pburkholder** [comment] 2015-06-03 15:01
@valerie-roske and others -- Please note the filename is `chefignore` with no dot in the name. I've seen references to `.chefignore`, which doesn't work.

**Comment by tyler-ball** [comment] 2015-06-03 18:35
@zl4bv Man, I totally messed this one up.  I haven't used a `chefignore` file before so I've just been guessing the whole time.  Did adding a `.kitchen` entry help you?

**Comment by zl4bv** [comment] 2015-06-03 20:01
> Did adding a .kitchen entry help you?

@tyler-ball Yes, it did help me. Well, I was seeing the same error and stack trace with my bundle directory but replacing `*/vendor/bundle/*` with `vendor/bundle` worked. 

Also, I eventually stumbled across some Opscode documentation on the `chefignore` file here if that's any help: https://docs.chef.io/chef_repo.html#chefignore-files

**Comment by tyler-ball** [comment] 2015-06-03 20:27
So it seems like the issue is to create a chefignore file that includes the `.kitchen` directory.  I'm going to file a new issue to have `kitchen init` and `chef generate cookbook` include the `.kitchen` directory.

**Closed by tyler-ball** 2015-06-03 20:27 UTC
Labels: Feedback Requested, Triaged, Windows

**Comment by valerie-roske** [comment] 2015-06-04 03:24
Thanks @tyler-ball and @zl4bv, this has solved my issue! :)

**Comment by vmariappan** [comment] 2016-02-10 10:54
Hi All,

I have a similar issue while logging into kitchen after converge. I do have all the setup as per your discussion above. I have the below files which is mentioned as not found.. Someone please advice. :)

C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:220:in `exec': No such file or directory - ssh (Errno::ENOENT)
        from C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:220:in `login'
        from C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/login.rb:39:in `call'
        from C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:56:in `perform'
        from C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:224:in `login'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:308:in `invoke_task'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `block in <top (required)>'
        from C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/errors.rb:154:in `with_friendly_errors'
        from C:/Users/vmariappan/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `<top (required)>'
        from C:/opscode/chefdk/bin/kitchen:16:in `load'
        from C:/opscode/chefdk/bin/kitchen:16:in `<main>'

**Comment by cheeseplus** [comment] 2016-02-10 12:12
@vmariappan your error is not like the ones above - if you are on a Windows host I believe you will need to ensure that you have SSH installed (the git package for windows brings this in). Also this should be it's own issue as opposed to piggybacking on a long closed issue

**Comment by vmariappan** [comment] 2016-02-10 12:25
Thanks for your response, i could login to my kitchen using Git Bash.

**Comment by cheeseplus** [comment] 2016-02-10 12:26
@vmariappan glad you got working! Let us know if we can help further.

**Comment by scuba10steve** [comment] 2016-08-29 19:30
I also encountered this problem after I had ran `berks install`
