### ISSUE TITLE
"file is of unknown type" error message should be "file not found"

### ISSUE THREAD

**Issue by dheerajdake** [test-kitchen/test-kitchen#1210] opened 2017-03-22 00:11 UTC
## Description
When I run kitchen converge, I get an error which is misleading. The error message should be properly described.  

I have an encrypted key in keys->encrypted_data_bag_secret. The folder is at a different location and I get this error. I moved the folder to the location specified in the error logs and it worked fine. It's just that the error message on the console is misleading. It took quite some time to get it right. 

## Kitchen Version

Test Kitchen version 1.15.0

```ruby
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [unknown file type: /Users/dheerajdake/Documents/sample/chef/keys/encrypted_data_bag_secret] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Platform Version

Mac OS Sierra 10.12.3

**Comment by cheeseplus** [comment] 2017-07-31 19:30
I am unable to reproduce this in current (1.16.0) kitchen - if the file doesn't exist it throws the error message:

```
Failed to complete #converge action: [No such file or directory @ rb_file_s_stat - /Users/cheeseplus/chef-repo/secrets/chef/encrypted_data_bag_secret] on default-centos7
```

Closing this but if you're still having issues with current versions please open a new issue and provide a reproducible test case.

**Closed by cheeseplus** 2017-07-31 19:30 UTC

**Comment by majormoses** [comment] 2017-11-16 17:39
I ran into this yesterday. I was using `kitchen-docker` and had something like this:
```
provisioner:
  name: shell
  data_path: .
  script: test/fixtures/bootstrap.sh
```

I had accidentally named the file `boostrap.sh` instead of `bootstrap.sh` and that fixed my problem. Maybe if I have some time later I could try creating a better reproduction case.
