### ISSUE TITLE
Permissions on /tmp/kitchen/* directories prevent convergence

### ISSUE THREAD

**Issue by BrynCooke** [test-kitchen/test-kitchen#396] opened 2014-03-27 14:52 UTC
When converging for the first time on vagrant the following directory structure is created on the vm at /tmp/kitchen/:

``` text
drwxr-xr-x  4 root    root    4096 Mar 27 14:37 backup
drwxr-xr-x  4 vagrant vagrant 4096 Mar 27 14:37 cache
-rw-------  1 root    root    1679 Mar 27 14:33 client.pem
-rw-r--r--  1 vagrant vagrant  620 Mar 27 14:33 client.rb
drwxr-xr-x  2 root    root    4096 Mar 27 14:33 clients
drwxr-xr-x 21 vagrant vagrant 4096 Mar 27 14:33 cookbooks
drwxr-xr-x  4 vagrant vagrant 4096 Mar 27 14:33 data_bags
-rw-r--r--  1 vagrant vagrant   31 Mar 27 14:33 dna.json
drwxr-xr-x  2 vagrant vagrant 4096 Mar 27 14:33 environments
drwxr-xr-x  2 root root 4096 Mar 27 14:33 nodes
drwxr-xr-x  2 vagrant vagrant 4096 Mar 27 14:33 roles
-rw-r--r--  1 vagrant vagrant 1679 Mar 27 14:33 validation.pem
```

Some directories are owned by root.

If I subsequently add nodes test data in /test/integration/<suite>/nodes/test.json then convergence will fail because the vagrant user doesn't have permissions to write to the nodes directory.

If I recreate the VM then the nodes directory is owned by the vagrant user and convergence will succeed from now on.

**Comment by kjwierenga** [comment] 2015-05-27 15:43
Yes, recreating the VM solved this issue for me too.

    kitchen destroy
    kitchen converge

**Comment by sethdmoore** [comment] 2015-06-15 19:09
Recreating the VM does 'solve' the problem' - however it really slows down development.
I don't want to destroy / reimport / reprovision a base box every time I change something / test in a cookbook I'm developing.

**Comment by kbaltrinic** [comment] 2015-06-16 18:05
+1  Hitting the same issue.

**Comment by ianrossi** [comment] 2015-07-13 16:57
+1 Same issue here

**Comment by hartfordfive** [comment] 2015-09-13 02:37
Same problem here :+1:

**Comment by SinisterLight** [comment] 2015-11-05 08:33
+1 Same

**Comment by qubitrenegade** [comment] 2015-12-08 19:17
+1, I'm having the same issue, although I'm using the kitchen-openstack driver.  The first run always seems to run without issue but any subsequent run ends with the permission denied error.

This seems to stem from running kitchen as a non-root user as I have no issues making multiple convergence runs when using the kitchen-vsphere driver.  I'm using identical images between openstack and vsphere, the primary difference is that kitchen-vsphere runs as root and kitchen-openstack runs as the 'centos' user.  If I update the vm to allow root login (openstack disables root login), and set my username to 'root' then subsequent `kitchen converge` runs are successful.

**Comment by cheeseplus** [comment] 2016-02-08 11:59
Is this condition still present? I'm looking to try to repro in the near future to confirm but if someone can provide repeatable steps with current versions I can get cracking on it sooner.

**Comment by vjdhama** [comment] 2016-06-17 14:48
I am still facing this issue on centos specifically. Second converge fails with 
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [scp: /tmp/kitchen/client.rb: Permission denied
]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by smitjainsj** [comment] 2016-10-13 16:14
just make sure "manifests" and module path are correct in .kitchen.yml file

**Comment by qubitrenegade** [comment] 2016-10-26 16:33
@vjdhama what order are you running your chef-client cookbooks? (or are you running chef-client cookbooks with test kitchen.)

I found that if I ran `chef-client::default` before `chef-client::config` test kitchen would fail when trying to start chef-client.  My solution was to set the client config directory to `/tmp/kitchen` in my .kitchen.yml.  But this caused the above permissions issue.  However, if I run `chef-client::config` before running `chef-client::default`, I find I don't have to set the config dir for in .kitchen.yml and I don't run into the same permissions issue.

**Comment by aespinosa** [comment] 2017-04-07 02:22
I am getting the same problem with `validation.pem`. I looked at it and it seems to be that it has been copied to the instance with missing permissions.

```
vagrant@default-debian-86:~$ ls -l /tmp/kitchen/validation.pem
-r--r--r-- 1 vagrant vagrant 1679 Apr  7 02:15 /tmp/kitchen/validation.pem
```

Doing a `chmod 644 /tmp/kitchen/validation.pem` did the trick for me to make subsequent converges work.

@cheeseplus maybe inspecting the generated files in the sandbox will help debug why the copied files have weird permissions.

**Comment by briancline** [comment] 2017-04-18 02:11
I only experienced this problem when:
1) running `kitchen converge` when there was no pre-existing VM and it had to provision a new one
2) creating a brand new `test/integration/nodes/leloomultipass.json` file after the converge, whereas I didn't previously have any node files created there (like, the folder didn't even exist prior)
3) re-running `kitchen converge` *without* destroying the same vm
4) kitchen explosion due to above permissions issue

Once I destroy and re-converge, it works. Afterwards, if I need to make changes to an *existing* node file, I do not experience the problem again -- the updated data is available during the converge. Perhaps it's isolated to new files.

My VMs were Ubuntu 12.04 and 14.04.

**Comment by aespinosa** [comment] 2018-08-03 16:44
Looks like the permissions are being inherited from whatever the  my omnibus installation contains:

```
workstation$ ls -l /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/support/dummy-validation.pem
-r--r--r-- 1 root root 1679 Jul 31  2018 /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.22.0/support/dummy-validation.pem
```

Changing it to `644` fixed my `validation.pem` having the proper permissions in the actual kitchen instances.

**Comment by cbrit** [comment] 2019-02-22 16:43
I'm having this issue with /tmp/kitchen/cache but it only occurs when I run kitchen from within a CentOS VM. I can run kitchen from my workstation (macOS) and it works fine.

**Comment by qubitrenegade** [comment] 2019-02-22 17:39
@cbrit does it happen on the first run or subsequent runs?  i.e.: do you get the same results running `kitchen test` as you do `kitchen converge && kitchen converge`?

**Comment by cbrit** [comment] 2019-02-22 19:12
@qubitrenegade It happens on the first run. It is specifically happing with the jenkins cookbook and I've seen the exact issue posted on that repo with no solution. The general answer seems to be "change your cache path" and a shrug.

**Comment by cheeseplus** [comment] 2019-02-22 20:45
chiming in here: the reason we've never been able to run this down is because we've never been able to reproduce it

The reason we've never been able to reproduce it is because we need a boatload of context that hasn't been provided to date like: Host OS version, ChefDK version, kitchen version (if not part of DK), instance OS version, instance OS image source, the driver (assuming vagrant/vbox), and the kitchen config. We also need that in a diagnostically reproducible snapshot and even then there are all sorts of wonky permissions or other environmental factors we simply can't see/get at.

Disabling the cache is still the best first solution but to actually run this down in a meaningful way we are simply lacking information.

**Comment by stgarf** [comment] 2019-04-08 21:06
> chiming in here: the reason we've never been able to run this down is because we've never been able to reproduce it
> 
> The reason we've never been able to reproduce it is because we need a boatload of context that hasn't been provided (in full for any given permutation) to date like: Host OS version, ChefDK version, kitchen version (if not part of DK), instance OS version, instance OS image source, the driver (assuming vagrant/vbox), and the kitchen config.
> 
> We also need that in a diagnostically reproducible snapshot (like a git repo) and even then there are all sorts of wonky permissions or other environmental factors we simply can't see/get at.
> 
> Disabling the cache is still the best first solution but to actually run this down in a meaningful way we are simply lacking information. There is also the distinct possibility that folks that have piled on the issue are also seeing what seems like similar behaviour but could be for very different reasons.

I've just hit this issue and @briancline describes the reproduction conditions perfectly.

**Comment by tas50** [comment] 2021-01-08 21:17
I'm going to close this out at this point. We haven't had a report of the problem on any modern Test Kitchen / Workstation combo. We'll need a repro case against the latest releases to move forward.

**Closed by tas50** 2021-01-08 21:17 UTC
Labels: Bug

**Comment by qubitrenegade** [comment] 2021-01-10 12:58
@tas50 you are amazing!

I think this was actually solved a long time ago, but admittedly I had
forgotten about this issue...  mea culpa!

I love that you're closing legacy issues!   Merry New Year!

- Q

**Comment by fleaz** [comment] 2022-12-08 13:53
> We haven't had a report of the problem on any modern Test Kitchen / Workstation combo.

Sorry for waking up such an old issue, but here I am :D 
I have exactly this bug with ChefDK 4.13.3, Vagrant 2.2.19, Testkitchen 2.10.0 

Let me know what I should provide to help debug this. I'm happy to help here.

**Comment by Stromweld** [comment] 2022-12-08 16:59
@fleaz are you not able to update. Those are all old versions. I'd recommend upgrading to chef-workstation latest and vagrant latest. chef-workstation comes with test-kitchen 3.3.2. That should fix your issue.
