### ISSUE TITLE
Error when converging "both URI are relative "

### ISSUE THREAD

**Issue by a-dawg** [test-kitchen/test-kitchen#1407] opened 2018-04-23 07:54 UTC
## Description

I cannot converge the following kitchen.yml  file using test kitchen and the puppets gems.

## Kitchen Version
1.20

## Kitchen file
```
driver:
  name: docker
  privileged: true
  use_sudo: true
  binary: docker

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata
  hiera_config_path: hiera.yml
  resolve_with_librarian_puppet: true

platforms:
  - name: centos-latest
    driver_config:
      image: centos:latest
      platform: centos 
      use_cache: true

suites:
  - name: default
    manifest: site.pp

```

## Error
```
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [both URI are relative] on default-centos-latest
```

## Backtrace

```
[2018-04-20T14:26:21.943081 #9102] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2018-04-20T14:26:21.943088 #9102] ERROR -- Kitchen: Message: Failed to complete #converge action: [both URI are relative]
E, [2018-04-20T14:26:21.943095 #9102] ERROR -- Kitchen: ----------------------
E, [2018-04-20T14:26:21.943102 #9102] ERROR -- Kitchen: ------Backtrace-------
E, [2018-04-20T14:26:21.943109 #9102] ERROR -- Kitchen: /usr/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge'
E, [2018-04-20T14:26:21.943116 #9102] ERROR -- Kitchen: /usr/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
E, [2018-04-20T14:26:21.943123 #9102] ERROR -- Kitchen: /usr/lib/ruby/vendor_ruby/faraday/connection.rb:406:in `build_exclusive_url'
E, [2018-04-20T14:26:21.943130 #9102] ERROR -- Kitchen: /usr/lib/ruby/vendor_ruby/faraday/rack_builder.rb:192:in `build_env'
E, [2018-04-20T14:26:21.943137 #9102] ERROR -- Kitchen: /usr/lib/ruby/vendor_ruby/faraday/rack_builder.rb:139:in `build_response'
E, [2018-04-20T14:26:21.943152 #9102] ERROR -- Kitchen: /usr/lib/ruby/vendor_ruby/faraday/connection.rb:377:in `run_request'
E, [2018-04-20T14:26:21.943163 #9102] ERROR -- Kitchen: /usr/lib/ruby/vendor_ruby/faraday/connection.rb:140:in `get'
E, [2018-04-20T14:26:21.943171 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/puppet_forge-2.2.9/lib/puppet_forge/v3/base.rb:69:in `request'
E, [2018-04-20T14:26:21.943178 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/puppet_forge-2.2.9/lib/puppet_forge/v3/base.rb:76:in `find_request'
E, [2018-04-20T14:26:21.943185 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/puppet_forge-2.2.9/lib/puppet_forge/v3/base.rb:82:in `find'
E, [2018-04-20T14:26:21.943193 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarian-puppet-3.0.0/lib/librarian/puppet/source/forge/repo_v3.rb:42:in `get_module'
E, [2018-04-20T14:26:21.943200 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarian-puppet-3.0.0/lib/librarian/puppet/source/forge/repo_v3.rb:19:in `get_versions'
E, [2018-04-20T14:26:21.943207 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarian-puppet-3.0.0/lib/librarian/puppet/source/forge/repo.rb:15:in `versions'
E, [2018-04-20T14:26:21.943215 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarian-puppet-3.0.0/lib/librarian/puppet/source/forge/repo.rb:42:in `manifests'
E, [2018-04-20T14:26:21.943222 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarian-puppet-3.0.0/lib/librarian/puppet/source/forge.rb:152:in `manifests'
E, [2018-04-20T14:26:21.943229 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/dependency.rb:155:in `cache_manifests!'
E, [2018-04-20T14:26:21.943236 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/dependency.rb:151:in `manifests'
E, [2018-04-20T14:26:21.943244 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:159:in `block in resolving_dependency_map_find_manifests'
E, [2018-04-20T14:26:21.943251 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:172:in `block (2 levels) in scope_resolving_dependency'
E, [2018-04-20T14:26:21.943258 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:186:in `block in scope_checking_manifests'
E, [2018-04-20T14:26:21.943266 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:230:in `scope'
E, [2018-04-20T14:26:21.943273 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:185:in `scope_checking_manifests'
E, [2018-04-20T14:26:21.943280 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:171:in `block in scope_resolving_dependency'
E, [2018-04-20T14:26:21.943288 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:230:in `scope'
E, [2018-04-20T14:26:21.943295 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:170:in `scope_resolving_dependency'
E, [2018-04-20T14:26:21.943309 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:158:in `resolving_dependency_map_find_manifests'
E, [2018-04-20T14:26:21.943317 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:65:in `do_resolve'
E, [2018-04-20T14:26:21.943324 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver/implementation.rb:50:in `resolve'
E, [2018-04-20T14:26:21.943332 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/resolver.rb:23:in `resolve'
E, [2018-04-20T14:26:21.943339 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/librarianp-0.6.4/lib/librarian/action/resolve.rb:31:in `run'
E, [2018-04-20T14:26:21.943346 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/kitchen-puppet-3.3.1/lib/kitchen/provisioner/puppet/librarian.rb:52:in `resolve'
E, [2018-04-20T14:26:21.943353 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/kitchen-puppet-3.3.1/lib/kitchen/provisioner/puppet_apply.rb:1408:in `block in resolve_with_librarian'
E, [2018-04-20T14:26:21.943363 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/kitchen-puppet-3.3.1/lib/kitchen/provisioner/puppet_apply.rb:1406:in `synchronize'
E, [2018-04-20T14:26:21.943371 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/kitchen-puppet-3.3.1/lib/kitchen/provisioner/puppet_apply.rb:1406:in `resolve_with_librarian'
E, [2018-04-20T14:26:21.943378 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/kitchen-puppet-3.3.1/lib/kitchen/provisioner/puppet_apply.rb:1255:in `prepare_modules'
E, [2018-04-20T14:26:21.943385 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/kitchen-puppet-3.3.1/lib/kitchen/provisioner/puppet_apply.rb:561:in `create_sandbox'
E, [2018-04-20T14:26:21.943393 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-04-20T14:26:21.943400 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:393:in `block in converge_action'
E, [2018-04-20T14:26:21.943408 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-04-20T14:26:21.943415 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-04-20T14:26:21.943430 #9102] ERROR -- Kitchen: /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2018-04-20T14:26:21.943438 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:497:in `action'
E, [2018-04-20T14:26:21.943445 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:389:in `converge_action'
E, [2018-04-20T14:26:21.943452 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2018-04-20T14:26:21.943460 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `each'
E, [2018-04-20T14:26:21.943467 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `transition_to'
E, [2018-04-20T14:26:21.943474 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:135:in `converge'
E, [2018-04-20T14:26:21.943481 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-04-20T14:26:21.943489 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-04-20T14:26:21.943496 #9102] ERROR -- Kitchen: /var/lib/gems/2.3.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'```

## Replication Case

kitchen converge

What I am doing wrong in my kitchen file?

**Comment by cheeseplus** [comment] 2018-04-23 11:02
The problem isn't one of configuration that I can tell, more a problem with the middleware that Librarian/librarian-puppet is trying to use. Unfortunately neither librarian or kitchen-puppet are supported by the test-kitchen team so there's not a lot of help we are able to offer since it's not really a problem of core test-kitchen.

**Comment by cheeseplus** [comment] 2018-07-30 16:47
Closing this out as it's a puppet-librarian issue and not one we can fix here.

**Closed by cheeseplus** 2018-07-30 16:47 UTC
