### ISSUE TITLE
Travis fails with a SCP error on the spec directory

### ISSUE THREAD

**Issue by ferrarimarco** [test-kitchen/test-kitchen#1187] opened 2017-01-24 08:42 UTC
## Description

I configured one of my Ansible roles (https://github.com/ferrarimarco/ansible-role-virtualbox) to be tested with test-kitchen and InSpec. It works fine on my local development environment:`kitchen converge` runs successfully for all the instances, but not on Travis.

While I was reporting the issue, I updated my test scripts to run a `kitchen diagnose --all` and a `kitchen diagnose --loader` as requested and that fixed the build. Kinda strange...

## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

```ruby
Test Kitchen version 1.15.0
```
This is valid for both my local development environment and for the Travis one.

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

On my local machine:
```ruby
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

On Travis CI:
```ruby
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

## Platform Version

* Local developent environment: Ubuntu 16.10 x64
* Travis CI: Ubuntu 14.04.4 x64

## Replication Case

See my [.kitchen.yml](https://github.com/ferrarimarco/ansible-role-virtualbox/blob/master/.kitchen.yml) and my [.travis.yml](https://github.com/ferrarimarco/ansible-role-virtualbox/blob/master/.travis.yml).

Test script diff: https://github.com/ferrarimarco/ansible-role-virtualbox/commit/3361e47cf0a6d481ceaf0cb89e4f4e8bedcb8442 

## Kitchen Output

Here is a link to the complete build logs
* Failing build: https://travis-ci.org/ferrarimarco/ansible-role-virtualbox/builds/194520297
* Fixed build: https://travis-ci.org/ferrarimarco/ansible-role-virtualbox/builds/194738958

The next snippet shows the relevant log part of the failing build:

```ruby
Transferring files to <default-ubuntu-1604>
/home/travis/.rvm/gems/ruby-2.3.1/gems/net-scp-1.2.1/lib/net/scp/upload.rb:40:in `upload_current_state': not a directory or a regular file: "/tmp/default-ubuntu-1604-sandbox-20170123-3779-90pfhl/spec" (Net::SCP::Error)
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-scp-1.2.1/lib/net/scp.rb:400:in `await_response_state'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/channel.rb:320:in `process'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:226:in `block in preprocess'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:226:in `each'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:226:in `preprocess'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:206:in `process'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:119:in `close'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/transport/ssh.rb:115:in `close'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:285:in `cleanup!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:205:in `run_action_in_thread'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
```

## Kitchen Diagnose
Available in the Travis build logs:
* Failing build: It's not available in the failing build as the command was not executed in that version of my role
* Fixed build: https://travis-ci.org/ferrarimarco/ansible-role-virtualbox/builds/194520297

UPDATE:
It happened again in this build: https://travis-ci.org/ferrarimarco/ansible-role-virtualbox/builds/194748084

Here is the diff between this and the older (working) build: https://github.com/ferrarimarco/ansible-role-virtualbox/compare/3361e47cf0a6d481ceaf0cb89e4f4e8bedcb8442...f33cbffaddd669344f846a16c6f79aa3558ecaba

UPDATE 2 (@cheeseplus):
It appears it's not related to the diagnostic commands. I tried the same in [this other build](https://travis-ci.org/ferrarimarco/ansible-role-bash-aliases/builds/195785117) (it's a different project), but it changed nothing

UPDATE 3:
this happens mostly in Ubuntu 16.04

UPDATE 4:
it seems to be a transitory issue because after restarting the build a couple of times it completes successfully...

**Comment by emoshaya-cognito** [comment] 2017-03-10 01:09
I'm also facing the exact same issue with ansible-kitchen

**Comment by zemmet** [comment] 2017-04-12 21:38
Same here with kitchen-ansible (1.46) on OS X Sierra 10.12.3 with vagrant driver

**Comment by cheeseplus** [comment] 2017-07-25 20:13
I've been unable to reproduce this and given the number of variables involved it's somewhere between a transient Travis only issue and an issue with kitchen-ansible itself. Given the age I'm closing this one but please do feel free to open a new one with current versions of kitchen (and more importantly net-scp/ssh) if this issue is still biting folks.

**Closed by cheeseplus** 2017-07-25 20:13 UTC
