### ISSUE TITLE
WinRM Transport requires the vagrant-winrm Vagrant plugin

### ISSUE THREAD

**Issue by devlife** [test-kitchen/test-kitchen#1109] opened 2016-09-01 17:43 UTC
## Description

I am trying to run `kitchen list` but am getting the following error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: WinRM Transport requires the vagrant-winrm Vagrant plugin to properly communicate with this Vagrant VM. Please install this plugin with: `vagrant plugin install vagrant-winrm' and try again.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

However, I have verified that `vagrant-winrm` is installed:

```
C:\source\cookbooks\role_windows_webserver [BETA-89-AddServerSpecTests +2 ~1 -0 !]> vagrant plugin list
vagrant-scp (0.5.7)
vagrant-share (1.1.5, system)
vagrant-winrm (0.7.0)
```
## Kitchen Version

Tell us which version of test-kitchen you are using (`kitchen --version`).  

``` ruby
Test Kitchen version 1.11.1
```
## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

``` ruby
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```
## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

``` ruby
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```
## Platform Version

Windows 10 1607 (Anniversary Update)
## Replication Case

Add the following in `.kitchen.yml` and run `kitchen list`:

```

---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: kensykora/windows_2012_r2_standard

suites:
  - name: default
    run_list:
      - recipe[role_windows_webserver::default]
    attributes:
```
## Kitchen Output

See [this gist](https://gist.github.com/devlife/c565580f77939af58070a6467fa8f248) for debug output
## Kitchen Diagnose

See [this gist](https://gist.github.com/devlife/6444a7e7f4b2779049adc8a1c07546ec)
## NOTE:

This repository is for core issues with the Test-Kitchen framework, so if the issue is with a plugin you may be referred to file the issue with the appropriate plugin.

**Comment by smurawski** [comment] 2016-09-02 17:28
You may need to pass `communicator: winrm` as part of the driver config if the box file doesn't have that by default in it's Vagrantfile.

**Comment by smurawski** [comment] 2016-09-02 17:28
Oh, and possibly map some ports.

**Comment by interpeix** [comment] 2016-11-22 09:08
I have the same problem, any workaround? the machine have in its vagranfile config.vm.communicator = "winrm" but the problem persists.

**Comment by mwrock** [comment] 2016-12-01 06:53
I suspect you are running an old version of vagrant. You shouldn't need that plugin with modern vagrant versions.

Also unrelated but likely to cause other problems, you should name your platform a string beginning with "win". Example:
```
platforms:
- name: windows-2012R2
  driver_config:
    box: kensykora/windows_2012_r2_standard
```

**Comment by ghbrown60640** [comment] 2017-01-10 23:02
Bumping on this because I'm having the same issues. Vagrant 1.9.1, test kitchen 1.14.2, chefdk 1.1.15,ruby 2.3.1p112 (embedded in chefdk). 
Kitchen and diagnose logs attached. 
testerrors is a sample cookbook. 
[testerrors.zip](https://github.com/test-kitchen/test-kitchen/files/697614/testerrors.zip)



[logs.zip](https://github.com/test-kitchen/test-kitchen/files/697613/logs.zip)

**Comment by mwrock** [comment] 2017-01-12 04:18
I was incorrect above. You do need the `vagrant-winrm` plugin. However you need to make sure that it is installed into the vagrant omnibus ruby. You can do this by running `vagrant plugin install vagrant-winrm`

**Comment by ghbrown60640** [comment] 2017-01-12 05:55
I have the plugin installed. Is it possible there's some sort of conflict
between the vagrant and chefdk Ruby libraries?

**Comment by ghbrown60640** [comment] 2017-01-13 18:55
Well I clearly have some path issue. I set my path to just vagrant and chefdk and it works. I'll see whats going on. thanks.

**Comment by davidski** [comment] 2017-02-06 04:53
@ghbrown60640 Did you find any additional info on this? I'm having a similar problem on a Win 10 host (ChefDK 1.2.22 also installed) whenever I have cygwin in my path. Removing `C:\cygwin64\bin` allows `kitchen list` to operate normally. Updates to cygwin have no effect.

**Comment by davidski** [comment] 2017-02-06 19:45
This looks to be related to color output from vagrant. On my working install, `vagrant plugin list` from `kitchen console` gives me `\n`delimited outputs. On my non-working install, the same command gives me delimited outputs with the ANSI reset codes (`\e[0m`) together with the newline. Manually tweaking https://github.com/test-kitchen/kitchen-vagrant/blob/77de176c04a64c8fbb968aeca197e90082e874ef/lib/kitchen/driver/vagrant.rb#L538 to call `vagrant --no-color plugin list` allows things to work. I'll take the tweak over to test-kitchen/kitchen-vagrant to see if this should be handled there.

Why one system is returning different output than the other is still a mystery to me.  🤔

**Comment by epopoee** [comment] 2017-03-07 10:26
both [davidski](https://github.com/davidski)'s cygwin workaround as well as [Ivadim](https://github.com/ivadim)'s regex fix for ...\kitchen\driver\vagrant.rb in [kitchen issue #240](https://github.com/test-kitchen/kitchen-vagrant/issues/240) confirmed to solve this issue

vagrant 1.9.2, kitchen 1.15.0

**Comment by cheeseplus** [comment] 2017-07-31 19:47
Closing this as merged https://github.com/test-kitchen/kitchen-vagrant/pull/309 and not a core kitchen issue.

**Closed by cheeseplus** 2017-07-31 19:47 UTC
Labels: Windows
