### ISSUE TITLE
'username:' keyword not respected during `kitchen exec -c 'command'`

### ISSUE THREAD

**Issue by bixu** [test-kitchen/test-kitchen#756] opened 2015-06-25 11:44 UTC
In the case shown below, although I'm setting a custom 'username' for one platform it's not getting used during SSH login during `kitchen exec`:

```
$ cat .kitchen.yml
---
driver_plugin: joyent
driver_config:
  joyent_username: "<%= ENV['SDC_ACCOUNT'] %>"
  joyent_keyfile: "<%= ENV['HOME'] %>/.ssh/id_rsa"
  joyent_keyname: "<%= ENV['SDC_KEY_ID'] %>"
  joyent_url: "<%= ENV['SDC_URL'] %>"
  joyent_flavor_id:  t4-standard-2G
provisioner:
  name: shell

platforms:
- name: smartos-64-14.3.0-smartmachine
  driver_config:
    joyent_image_id: 62f148f8-6e84-11e4-82c5-efca60348b9f

- name: ubuntu-14.04-smartmachine
  driver_config:
    joyent_image_id: a21a64a0-0809-11e5-a64f-ff80e8e8086f

- name: ubuntu-14.04-virtualmachine
  driver_config:
    joyent_image_id: c864f104-624c-43d2-835e-b49a39709b6b
    username: ubuntu

suites:
  - name: ubuntu
    provisioner:
      script: scripts/ubuntu.sh
    excludes:
      - smartos-64-14.3.0-smartmachine

  - name: smartos
    provisioner:
      script: scripts/smartos.sh
    excludes:
      - ubuntu-14.04-smartmachine
      - ubuntu-14.04-virtualmachine

$ kitchen exec -c 'java -version'
-----> Execute command on ubuntu-ubuntu-1404-smartmachine.
       java version "1.7.0_79"
       OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
       OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
-----> Execute command on ubuntu-ubuntu-1404-virtualmachine.
       Please login as the user "ubuntu" rather than the user "root".

-----> Execute command on smartos-smartos-64-1430-smartmachine.
       openjdk version "1.7.0-internal"
       )
       OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

**Comment by sawanoboly** [comment] 2015-07-01 07:29
@bixu 

Hi,
If you are using test-kitchen 1.4 or later, Could you try add transport section to ubuntu for `kitchen exec`? Such as below.

```
  - name: ubuntu-14.04-virtualmachine
    driver_config:
      joyent_image_id: c864f104-624c-43d2-835e-b49a39709b6b
      username: ubuntu
    transport:
      username: ubuntu
```

**Comment by bixu** [comment] 2015-07-01 15:33
You are correct, setting the 'transport' option fixes this (although this still feels bug-like to me from a user perspective).

**Comment by sawanoboly** [comment] 2015-07-02 05:12
Almost commands which maintained by test-kitchen org members are kept compatibility with legacy plugins.
But few commands which added via PR by out of org are low priority to keep backward compatibility. imho. For example, `exec` command added by me.

The kitchen-joyent plugin looks like didn't update to new structures of 1.4.x yet. 
If it will update for 1.4, attributes of ssh will be assembled to transport section. Maybe.

P.S. 
Since I'm not a member of test-kitchen, I can't close the issue.

**Comment by bixu** [comment] 2015-07-02 06:46
@sawanoboly, do you have some pointers on where to start updating the kitchen-joyent driver?  I have contributor status but am not (yet) familiar with the code.

**Comment by sawanoboly** [comment] 2015-07-02 07:15
@bixu 

hmm.. In my case, I usually see `base.rb` when creating and updating my plugins. e.g. `provisioner/base.rb`, `verifier/base.rb`
It's difficult to update plugin from 1.3.x to 1.4.x, because there are many changes (but changes seem useful).
Maybe, building from copied `base.rb` is easier than update directly. :sweat:

**Comment by joshzitting** [comment] 2015-09-29 18:47
Any progress on this? We are seeing this issue too!

**Comment by ramonskie** [comment] 2015-10-02 08:32
use this option
```
platforms:
  transport:
    username: ubuntu
  driver_config:
    ........
```

**Comment by joshzitting** [comment] 2015-10-02 18:12
@ramonskie We have done that. I just wanted to know if there was a permanent fix for it! thanks!

**Comment by cheeseplus** [comment] 2016-09-04 17:57
The issue is older drivers not respecting the transport changes as described above and if a custom username is needed, it should be set there and used throughout.

Closing.

**Closed by cheeseplus** 2016-09-04 17:57 UTC
Labels: No_Changelog
