### ISSUE TITLE
VBOX fails if generated instance name exceeds 64 characters

### ISSUE THREAD

**Issue by scoopex** [test-kitchen/test-kitchen#1383] opened 2018-03-09 07:08 UTC
I am currently using:

- vagrant 2.0.2
- virtualbox 5.2.8
- kitchen 1.20.0

I am using test-kitchen to test our puppetcode and i am pretty happy with it. 
Thanks for maintaining this project.

I updated kitchen, vagrant, and virtualbox to the listed releases at the beginning of the week.
Kitchen or vagrant now creates new instance names which look like this: default-ubuntu-hosting-basesetup_default_1520575332373_26663
The last group of numbers in the instance name seems to be new.

Just review my configs at:
- https://github.com/scoopex/puppet-kitchen_template/blob/master/.kitchen.yml
- https://github.com/scoopex/puppet-hosting_basesetup

If the entire instance name exceeds 64 characters, i am getting the following result:
```
$ kitchen create default-ubuntu-1604-hosting-basesetup
-----> Starting Kitchen (v1.20.0)
-----> Creating <default-ubuntu-1604-hosting-basesetup>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Checking if box 'ubuntu/xenial64' is up to date...
       ==> default: Clearing any previously set forwarded ports...
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       There was an error while executing `VBoxManage`, a CLI used by Vagrant
       for controlling VirtualBox. The command and stderr is shown below.
       
       Command: ["startvm", "7769e2b8-dd3c-4df0-beab-3a3db7285ee4", "--type", "headless"]
       
       Stderr: VBoxManage: error: The specified string / bytes buffer was to small. Specify a larger one and retry. (VERR_CFGM_NOT_ENOUGH_SPACE)
       VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
STDERR: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "7769e2b8-dd3c-4df0-beab-3a3db7285ee4", "--type", "headless"]

Stderr: VBoxManage: error: The specified string / bytes buffer was to small. Specify a larger one and retry. (VERR_CFGM_NOT_ENOUGH_SPACE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
---- End output of vagrant up --provider virtualbox ----
Ran vagrant up --provider virtualbox returned 1] on default-ubuntu-1604-hosting-basesetup
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

The error message is a bit misleading. After shortening the name in the platform definition in a way that the resulting autogenerated instance name is 64 characters or below the problem disappears.

I have currently no idea where this problem is really located - it seems that virtualbox changed the possible amount of characters for instance names.

See also: https://github.com/scoopex/puppet-kitchen_template/issues/6

**Comment by cheeseplus** [comment] 2018-03-09 11:16
While we might be able to mitigate this some, the problem is definitely upstream https://github.com/hashicorp/vagrant/issues/9524

**Comment by cheeseplus** [comment] 2018-03-09 19:28
Closing here and opened under https://github.com/test-kitchen/kitchen-vagrant/issues/347 - still an upstream problem but this is where we would fix/workaround if needed.

**Closed by cheeseplus** 2018-03-09 19:28 UTC
Labels: Blocked
