### ISSUE TITLE
WinRM commandline limits can break Windows bootstrapping

### ISSUE THREAD

**Issue by jf647** [test-kitchen/test-kitchen#811] opened 2015-08-06 17:31 UTC
On TK 1.4.1:

```
-----> Starting Kitchen (v1.4.1)
-----> Creating <default-win2012r2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'win2012r2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-example-default-win2012r2_default_1438881656026_31809
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 3389 => 3389 (adapter 1)
           default: 5985 => 5985 (adapter 1)
           default: 22 => 2222 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Machine not provisioning because `--no-provision` is specified.
       [WinRM] Established
       Vagrant instance <default-win2012r2> created.
       Finished creating <default-win2012r2> (1m18.77s).
-----> Converging <default-win2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.3.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading package from https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-12.4.1-1.msi
       Download complete.
```

On TK 1.4.2:

```
-----> Starting Kitchen (v1.4.2)
-----> Creating <default-win2012r2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'win2012r2'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-example-default-win2012r2_default_1438881568509_73724
       ==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
       ==> default: Fixed port collision for 5985 => 5985. Now on port 2201.
       ==> default: Fixed port collision for 22 => 2222. Now on port 2202.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 3389 => 2200 (adapter 1)
           default: 5985 => 2201 (adapter 1)
           default: 22 => 2202 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Machine not provisioning because `--no-provision` is specified.
       [WinRM] Established
       Vagrant instance <default-win2012r2> created.
       Finished creating <default-win2012r2> (1m15.91s).
-----> Converging <default-win2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.3.0...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing validation.pem
       Preparing client.rb
$$$$$$ The command line is too long.
>>>>>> Converge failed on instance <default-win2012r2>.
>>>>>> Please see .kitchen/logs/default-win2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [$env:http_proxy = "http://proxy.address.here"
$env:HTTP_PROXY = "http:/proxy.address.here:8181"
$env:https_proxy = "http://proxy.address.here:8181"
$env:HTTPS_PROXY = "http://proxy.address.here:8181"
$chef_metadata_url = "https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2008r2&v=latest"
$chef_omnibus_root = "$env:systemdrive\opscode\chef"
$msi = "$env:TEMP\chef-true.msi"
$pretty_version = "install only if missing"
$version = "true"

Function Check-UpdateChef($root, $version) {
  if (-Not (Test-Path $root)) { return $true }
```

This is then followed by ~200 lines of Powershell.

Any further info I can provide to help diagnose?

**Comment by smurawski** [comment] 2015-08-06 23:54
@jf647 Is this with the same .kitchen.yml across both runs?  (I'm guessing so.) Could you provide the output of kitchen diagnose from 1.4.1 and from 1.4.2? 

I don't see anything obvious between 1.4.1 and 1.4.2 in the provisioner code or transport code, so I'd like to see what kitchen thinks the config values are.

**Comment by ksubrama** [comment] 2015-08-13 00:24
If the powershell snippet in TK 1.4.2 happens to be greater than 8191 character (while the one in TK 1.4.1 is less than that), that would be one reason.

**Comment by jf647** [comment] 2015-08-13 00:46
Based on this line:

```
$$$$$$ The command line is too long.
```

That definitely seems to be the problem.  I'll try to run this tomorrow with log level debug and see how long the snippet is in 1.4.1 vs 1.4.2

**Comment by dougireton** [comment] 2015-10-02 05:48
I can confirm this problem in TK 1.4.2. I have pinned to 1.4.1 as a workaround. I'll run 1.4.2. in debug mode and 1.4.1 in debug mode and paste results soon.

**Comment by jf647** [comment] 2015-10-02 16:06
IIRC, the issue was probably the use of a proxy.  I suspect that the default powershell generated by TK 1.4.2 is dangerously close to the 8191 character limit.  Adding in the `$env:VAR=value` bits pushes it over.

This presumably means that TK 1.4.1 generated a smaller chunk of powershell such that length(script + envlines) <= 8191.

**Comment by ksubrama** [comment] 2015-10-02 18:03
That would make sense. The 8191 limit is not the number of characters we write but the number of characters after shell variables have been expanded.  We can't actually know what the expansion would look like until it's performed on the target node.  I tried to throw in some heuristics but if we're printing out long environment variables (like %PATH%), then it may very well push it over 8191 characters.  I'll try to update the heuristic.

**Comment by paul1994** [comment] 2015-10-08 18:24
One more on the Confirmation or 1.4.2 causing issues.. I am going to pin to 1.4.1 and see what happens.

**Comment by dmitrievav** [comment] 2015-10-16 15:00
Hey Guys! If someone can provide step by step workaround, it would be very appreciated.

**Comment by dmitrievav** [comment] 2015-10-24 11:05
# workaround:
brew cask install chefdk --force
chef gem install test-kitchen -v 1.4.1
chef gem uninstall test-kitchen -v 1.4.2

## change the file:
diff -u kitchen.bak /usr/local/bin/kitchen
--- kitchen.bak	2015-10-24 13:55:21.000000000 +0300
+++ /usr/local/bin/kitchen	2015-10-24 13:48:51.000000000 +0300
@@ -6,9 +6,9 @@
 gem "net-ssh", "= 2.9.2"
 gem "safe_yaml", "= 1.0.4"
 gem "thor", "= 0.19.1"
-gem "test-kitchen", "= 1.4.2"
+gem "test-kitchen", "= 1.4.1"

-spec = Gem::Specification.find_by_name("test-kitchen", "= 1.4.2")
+spec = Gem::Specification.find_by_name("test-kitchen", "= 1.4.1")
 bin_file = spec.bin_file("kitchen")

 Kernel.load(bin_file)

## check
chef -v
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.1

**Comment by ksubrama** [comment] 2015-10-28 17:34
As mentioned in the referenced issue above, the situation is even more restricted since we can only use ~3000 characters instead of 8191 because we base64 encode the utf16 command string.  The ps1 file being used here is around 3000 characters (there are new-lines in there and I don't really know how they get handled) which makes things go pear shaped with the extra env vars.

**Comment by mwrock** [comment] 2015-10-28 17:40
Yup this has come up in #854 as well where test-kitchen prepends proxy variables. If your [proxy URLs are too long, you are out of luck. It seems like moving this large command to a file that is transferred by the provisioner would be a sensible approach to avoid this.

**Closed** 2017-12-18 21:35 UTC
Labels: Bug, Provisioner: Chef, Windows
