### ISSUE TITLE
Need support for keepalive for ssh connections

### ISSUE THREAD

**Issue by adamb-altiscale** [test-kitchen/test-kitchen#585] opened 2015-01-21 20:20 UTC
We have an intermittent hang with one of our kitchen-ssh instances. Specifically it happens after the network service is restarted during a converge.

Adding support for keepalive options available in Net::ssh would at least allow the connection to terminate rather than hang our jenkins jobs.

I initially brought this up over at https://github.com/neillturner/kitchen-ssh, and it was suggested that this was the right place for this issue to be addressed.

See https://github.com/neillturner/kitchen-ssh/issues/3#issuecomment-70899936 for

**Comment by tyler-ball** [comment] 2015-02-13 21:58
Closing this as a duplicate of https://github.com/test-kitchen/test-kitchen/pull/608.  You can read the thread in there, but @fnichol has a solution and we are working to get it merged into master.

**Closed by tyler-ball** 2015-02-13 21:58 UTC
