### ISSUE TITLE
safe_yaml is broken with newer psych

### ISSUE THREAD

**Issue by gmmeyer** [test-kitchen/test-kitchen#1327] opened 2017-12-04 22:29 UTC
## Description

safe_yaml errors out for me in almost every currently supported ruby I've tested on macos (and on linux). This is a known issue in safe_yaml, which appears to be abandoned at this point: https://github.com/dtao/safe_yaml/issues/80.

It's very hard to get test kitchen to work because of this.

I have even replicated this with the chefdk on ubuntu xenial.

## Kitchen Version

```ruby
1.19.2
```

## ChefDK Version

```ruby
2.4.17
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
```

## Platform Version

MacOS 10.12.6
Ubuntu Xenial

## Replication Case

Install ruby with RVM on a docker image. Install test kichen. Run any kitchen command.

## Kitchen Output

The relevant output of the test-kitchen run or a link to a gist of the entire run, if there is one.

The debug output (kitchen -l debug) may be useful, but please link to a gist, or truncate it.

Please do not paste the full run out put here.  If the full output would be useful, link to it in a gist.

```ruby
$ kitchen diagnose --no-instances --loader
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:22:in `<class:Date>': uninitialized constant SafeYAML::Parse::Date::DateTime (NameError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:3:in `<class:Parse>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:2:in `<module:SafeYAML>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:1:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:14:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/loader/yaml.rb:21:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen.rb:42:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:21:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:10:in `<top (required)>'
        from /opt/chefdk/bin/kitchen:255:in `load'
        from /opt/chefdk/bin/kitchen:255:in `<main>'
```

## Kitchen Diagnose

Cannot run this, cannot run the cli.

**Comment by coderanger** [comment] 2017-12-04 22:37
Please include the actual error trace or output of some kind.

**Comment by gmmeyer** [comment] 2017-12-04 23:17
@coderanger I have updated my description with the error output

**Comment by coderanger** [comment] 2017-12-04 23:32
I am unable to reproduce this using ChefDK on the `ubuntu:16.04` Docker image.

**Comment by coderanger** [comment] 2017-12-05 01:13
Though if it is the same bug as you linked, we can probably add a `require 'date'` somewhere early to fix it.

**Comment by gmmeyer** [comment] 2017-12-05 15:35
I'm pretty sure it is.

I think I know why you can't reproduce, though. It seems to only happen when I have a Gemfile and do `bundle exec kitchen`. If I do `bundle install` and then just run kitchen directly it will work.

**Comment by coderanger** [comment] 2017-12-05 19:04
What does your Gemfile look like?

**Comment by xeron** [comment] 2017-12-06 01:29
I started getting the same error recently:

```
$ kitchen diagnose --no-instances --loader
/Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:22:in `<class:Date>': uninitialized constant SafeYAML::Parse::Date::DateTime (NameError)
Did you mean?  SafeYAML::Parse::Date::DATE_MATCHER
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:3:in `<class:Parse>'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:2:in `<module:SafeYAML>'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:1:in `<top (required)>'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:14:in `<top (required)>'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.19.2/lib/kitchen/loader/yaml.rb:21:in `<top (required)>'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.19.2/lib/kitchen.rb:42:in `<top (required)>'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:21:in `<top (required)>'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/gems/test-kitchen-1.19.2/bin/kitchen:10:in `<top (required)>'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/bin/kitchen:23:in `load'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/bin/kitchen:23:in `<main>'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ilarionov/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

I don't have `Gemfile` and don't use ChefDK, just install kitchen using rvm/gem.

```
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
test-kitchen (1.19.2)
```

Not even sure what changed, it was working several days ago. Probably `gem update` did something.

**Comment by xeron** [comment] 2017-12-06 01:45
Wiped my gemset, did:

```
$ gem install test-kitchen berkshelf dep_selector dep-selector-libgecode
…
$ kitchen --version
Test Kitchen version 1.19.2
$ gem outdated
bigdecimal (1.3.0 < 1.3.2)
celluloid (0.16.0 < 0.17.3)
celluloid-io (0.16.2 < 0.17.3)
json (2.0.4 < 2.1.0)
net-ssh-gateway (1.3.0 < 2.0.0)
openssl (2.0.5 < 2.0.6)
psych (2.2.2 < 3.0.1)
rdoc (5.0.0 < 6.0.0)
rspec_junit_formatter (0.2.3 < 0.3.0)
thor (0.19.1 < 0.20.0)
timers (4.0.4 < 4.1.2)
```

Updated 1 by 1. Reproduced issue after updating `psych` to `3.0.1`.

**Comment by labkey-ians** [comment] 2017-12-06 18:31
Looks like there is a pull request on SafeYAML, but I'm not holding much hope for it to get merged.

**Comment by xeron** [comment] 2017-12-06 23:34
@coderanger thank you, but let me quote my previous answer to the same recommendation from you:

> Thank you for proposal. I don't use ChefDK for purpose and I have no issues with my environment.

I'm just trying to help you to debug the issue here. I already fixed it in my environment by downgrading `psych`.

**Comment by coderanger** [comment] 2017-12-07 04:36
I also do not use ChefDK so there is likely something more complex about your environment. Like you mentioned Ruby 2.2 but @gmmeyer was using 2.4? Notably psych does not actually appear in the depgraph I use (but I'm not pulling in berks or gecode), so maybe check what's pulling that in as a gem?

**Comment by xeron** [comment] 2017-12-07 19:28
@coderanger sorry for confusion with versions, I use `ruby 2.4.2p198`, `2.2.2` is the version of `psych` bundled into ruby which works for me, but if I update it to `3.0.1` then `test-kitchen` stops working.

**Comment by coderanger** [comment] 2017-12-07 23:34
Got it, if I add `gem 'psych', '3.0.1'` to my Gemfile I can repro locally. Going to update the title to make things clearer :)

**Closed** 2017-12-08 11:38 UTC
