### ISSUE TITLE
Shell Provisoner Fails on Windows due to execute bit

### ISSUE THREAD

**Issue by darkn3rd** [test-kitchen/test-kitchen#1413] opened 2018-05-18 06:51 UTC
## Description

Unable to do `kitchen converge` with `bootstrap.sh` script crafted on Windows.   

Workaround is to:

```bash
pushd .kitchen/kitchen-vagrant/default-centos-74
vagrant ssh
chmod +x /tmp/kitchen/bootstrap.sh
logout
popd
kitchen converge
```

## Kitchen Version

```ruby
Test Kitchen version 1.19.2
```

## ChefDK Version

```ruby
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Ruby Version

If you are not using test-kitchen via ChefDK, please provide the output of ruby --version.

```ruby
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
```

## Platform Version

Tell us which Operating System distribution and version test-kitchen is running on.

```
Microsoft Windows
Version 1709 (OS Build 16299.431)
```

## Replication Case

```yaml
---
driver:
  name: vagrant

provisioner:
  name: shell

verifier:
  name: inspec

platforms:
  - name: centos-7.4

suites:
  - name: default
    verifier:
      inspec_tests:
        - /path/to/test
```

```bash
#!/usr/bin/env bash
yum install -y java-1.7.0-openjdk-devel
```

## Kitchen Output

```E, [2018-05-17T23:06:03.730805 #15680] ERROR -- default-centos-74: ----------------------
E, [2018-05-17T23:06:03.730805 #15680] ERROR -- default-centos-74: ------Backtrace-------
E, [2018-05-17T23:06:03.731317 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
E, [2018-05-17T23:06:03.731476 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/provisioner/base.rb:86:in `call'
E, [2018-05-17T23:06:03.731590 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:393:in `block in converge_action'
E, [2018-05-17T23:06:03.731590 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-05-17T23:06:03.731590 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-05-17T23:06:03.731590 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-05-17T23:06:03.731590 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
E, [2018-05-17T23:06:03.731590 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:389:in `converge_action'
E, [2018-05-17T23:06:03.731590 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2018-05-17T23:06:03.731590 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:135:in `converge'
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: ----End Backtrace-----
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: ---Nested Exception---
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: Class: Kitchen::Transport::SshFailed
E, [2018-05-17T23:06:03.732081 #15680] ERROR -- default-centos-74: Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /tmp/kitchen/bootstrap.sh
']```

**Comment by thewyzard44** [comment] 2018-05-19 06:54
duplicate of #931 
potentially resolved with #1381 

I'll ping and see if we can push this through

**Comment by nimDevOps** [comment] 2018-06-19 15:22
I also faced this issue recently, here is another fast possible solution I've just tried:
change the command from
     sudo -E /tmp/kitchen/bootstrap.sh
to
     sudo -E /bin/sh /tmp/kitchen/bootstrap.sh

/bin/sh is default shell for many systems, and if we would like to change it, it's very easy through additional/optional attribute in .kitchen.yml file, something like:

provisioner:
  name: shell
  shell_type: </bin/sh|/bin/bash|/bin/csh|/bin/ksh>

**Comment by cheeseplus** [comment] 2018-06-21 17:48
Resolving with https://github.com/test-kitchen/test-kitchen/pull/1381 but we can always re-open if need be

**Closed by cheeseplus** 2018-06-21 17:48 UTC

**Comment by nimDevOps** [comment] 2018-07-05 15:54
The issue is still there with 1.22.0, see my comment on https://github.com/test-kitchen/test-kitchen/pull/1381
