### ISSUE TITLE
Invoking Rake tasks with concurrency?

### ISSUE THREAD

**Issue by jeffbyrnes** [test-kitchen/test-kitchen#799] opened 2015-07-31 20:23 UTC
Similar to #374, I’d love to know how to use Rake to concurrently run my test suites.

**Comment by gadgetmg** [comment] 2015-10-01 13:27
This works for me:

```ruby
require 'kitchen'

task :concurrent do
  Kitchen.logger = Kitchen.default_file_logger
  @loader = Kitchen::Loader::YAML.new(project_config: './.kitchen.yml')
  config = Kitchen::Config.new(loader: @loader)
  threads = []
  config.instances.each do |instance|
    threads << Thread.new do
      instance.test(:always)
    end
  end
  threads.map(&:join)
end
```

**Comment by cheeseplus** [comment] 2016-02-08 11:43
Closing this as dupe of #374 but it's definitely something we should add.

**Closed by cheeseplus** 2016-02-08 11:43 UTC
