### ISSUE TITLE
WinRM execution expired

### ISSUE THREAD

**Issue by jeffreycoe** [test-kitchen/test-kitchen#1331] opened 2017-12-12 20:03 UTC
## Description

We have Jenkins instances using ChefDK 2.4.17 which launch Test Kitchen (using the command kitchen test -d always) as part of our CI pipeline. We have a few cookbooks which attempt to provision a Windows Server 2012 R2 server in our OpenStack instance and execute InSpec tests.

We keep having failures after the VM is deployed, and while it's attempting to install the Chef Client. It looks like a timeout value is reached before the Chef Client install completes.  We've tested Chef Client versions 12.14.89 and 13.6.4. It seems to take a minute (or a little over a minute) when it times out.  This can be intermittent where sometimes it will complete, but the majority of the time it will fail.

I'm not sure if this is the correct area to report this issue, so please let me know if this needs to be reported elsewhere.

## Kitchen Version

```ruby
Test Kitchen version 1.19.2
```

## ChefDK Version

If you are running test-kitchen via ChefDK, `chef --version` will provide additional relevent version details.

```ruby
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Platform Version

Test Kitchen is configured on a Jenkins server running RHEL 6.8

## Replication Case

Execute kitchen test and preconfigure .kitchen.yml file and userdata.txt file with information outlined in the below gist:

https://gist.github.com/jeffreycoe/99364e1e6d9ce249b6debe4914a414df

## Kitchen Output

Gist: https://gist.github.com/jeffreycoe/99364e1e6d9ce249b6debe4914a414df

## Kitchen Diagnose

Gist: https://gist.github.com/jeffreycoe/99364e1e6d9ce249b6debe4914a414df

**Comment by cheeseplus** [comment] 2018-03-09 18:13
After some expert sleuthing by @stuartpreston it seems this might be happening upstream.

The `[execution expired]` message comes from the Ruby ::Timeout Class and looking at httpclient, someone switched from Kernel.Timeout to this in late 2015.  https://github.com/nahi/httpclient/blame/1fc7b579406e0185b98adcaf3af7b2d28da566ba/lib/httpclient/session.rb#L870

Apparently the Ruby Timeout doesn't derive from StandardError so that rescue is probably wrong and perhaps dropping winrm's dep to 2.7.0 would get us in a better spot.


```
D      ------Backtrace-------
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:870:in `readpartial'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:870:in `block in read_body_length'
D      C:/Ruby24-x64/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:868:in `read_body_length'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:573:in `get_body'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient.rb:1243:in `do_get_block'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient.rb:1021:in `block in do_request'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient.rb:1016:in `do_request'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient.rb:858:in `request'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/httpclient-2.7.2/lib/httpclient.rb:761:in `post'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/http/transport.rb:177:in `send_request'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/wsmv/receive_response_reader.rb:95:in `send_get_output_message'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/wsmv/receive_response_reader.rb:63:in `read_response'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/psrp/receive_response_reader.rb:41:in `read_message'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/psrp/receive_response_reader.rb:60:in `block in read_output'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/wsmv/receive_response_reader.rb:75:in `with_output'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/psrp/receive_response_reader.rb:59:in `read_output'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:82:in `block in run'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:132:in `with_command_shell'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:81:in `run'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/transport/winrm.rb:241:in `execute_with_exit_code'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/transport/winrm.rb:107:in `execute'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/transport/base.rb:128:in `execute_with_retry'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/provisioner/base.rb:77:in `block in call'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/transport/base.rb:98:in `initialize'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/transport/winrm.rb:87:in `initialize'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/transport/winrm.rb:445:in `new'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/transport/winrm.rb:445:in `create_new_connection'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/transport/winrm.rb:74:in `connection'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/provisioner/base.rb:70:in `call'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:393:in `block in converge_action'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:498:in `block in action'
D      C:/Ruby24-x64/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:497:in `action'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:389:in `converge_action'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:368:in `block in transition_to'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `each'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `transition_to'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:135:in `converge'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `public_send'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

Thus far it's the best lead on this issue so we're investigating further.

**Comment by robbkidd** [comment] 2018-03-09 19:42
@jeffreycoe Can you dig up the `.kitchen/logs/Win2012R2.log` from the Jenkins job run for this failure? That will have timestamps on for the output activity and might help us figure out what timeout we're hitting.

**Comment by JCapriotti** [comment] 2018-06-27 00:00
@robbkidd I started hitting this error today with ChefDK 3.0.36 on Windows. Previous version (2.5.3) worked fine. 

The first file in this Gist is the stacktrace that should be similar to what you requested. The second is a successful run with ChefDK 2.5.3
https://gist.github.com/JCapriotti/bd28b27f0c16c8f766f634af4e841b3f

I'm not sure if this is in anyway related or not, but wanted to mention it. Looking at the successful run, it takes just under a minute for the WinRM connection to succeed, and in the error it takes about 1 minute, 52 seconds to fail. So it seems like the problem is with WinRM? Not sure what you were thinking as far as the cause...

**Comment by JCapriotti** [comment] 2018-06-27 02:19
I was trying to dig into this more...

I noticed the debug log on success:
> [WinRM]  opening remote shell on https://10.144.21.180:5986/wsman

And failure:
> [WinRM] opening remote shell on http://10.144.24.97:5986/wsman

Note "http" vs "https"

This is the relevant .kitchen.yml:
```
transport:
  name: 'winrm'
  elevated: true
  username: 'Administrator'
  ssh_key: ~/.ssh/test-kitchen
  port: 5986
  endpoint_template: https://%{hostname}:%{port}/wsman
```

Removing the `port` and `endpoint_template` fixes the issue and this what the log shows:
>  [WinRM] opening remote shell on http://10.144.17.99:5985/wsman

Unfortunately I'm not the creator of the cookbook so I don't know why things are the way they are... but I wasn't able to find any documentation on the `endpoint_template` setting. Based on my results, maybe it is ignored, and only `port` is important?

Again, this may be 100% irrelevant, but as far as my issue goes I at least have a workaround (or a fix to some improper settings).

**Comment by jeffreycoe** [comment] 2019-06-06 19:22
Sorry everyone for the extremely long delay in responding. If I remember correctly, we were having a network issue with our OpenStack instance back then which resulted in the errors I originally reported.

I do remember that not having the ability to set the WinRM `operation_timeout` and `receive_timeout` was an issue and would have helped.  Now that those options have been added with #1493, I think we can close this issue out now. 

Thank you everyone for your help!

**Comment by cheeseplus** [comment] 2019-06-06 19:57
Thanks for following up!

Closing...

**Closed by cheeseplus** 2019-06-06 19:57 UTC
Labels: Windows

**Comment by thumperward** [comment] 2019-06-07 08:11
This still doesn't resolve the issue. If the Chef run takes more than an hour, WinRM still times out. Setting `receive_timeout` and `operation_timeout` to high values has no effect.

**Comment by cheeseplus** [comment] 2019-06-07 14:17
That sounds like a different issue than the one that was reported and a fundamental winrm limitation that is entirely out of scope for kitchen to address, especially the nature of the problem reported here. If you'd like to open an issue specifically for this (assuming it even could be fixed) then please do as the comment doesn't really move anything forward.
