### ISSUE TITLE
Gems from metadata.rb are not installed when running via test kitchen.

### ISSUE THREAD

**Issue by danieljimenez** [test-kitchen/test-kitchen#1203] opened 2017-03-07 04:25 UTC
## Description

Gems from metadata.rb are not installed when running via test kitchen.

## Kitchen Version

```ruby
Test Kitchen version 1.16.0
```

## Ruby Version

```ruby
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
```

## Platform Version

ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

Using a centos 7.1 test box, vagrant, virtual box.

## Replication Case

Add `gem 'aws-sdk'` to any cookbook's metadata.rb, add the require statement to any recipe. Call that recipe in test kitchen.

## Kitchen Output

```ruby
        ================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/foreflight_nginx/recipes/proxy.rb
         ================================================================================
         
         LoadError
         ---------
         cannot load such file -- aws-sdk
         
         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/foreflight_server/libraries/helpers.rb:2:in `decrypt'
           /tmp/kitchen/cache/cookbooks/foreflight_server/libraries/helpers.rb:19:in `decrypt_base64'
           /tmp/kitchen/cache/cookbooks/foreflight_nginx/libraries/helpers.rb:19:in `decrypt_key'
           /tmp/kitchen/cache/cookbooks/foreflight_nginx/recipes/service_discovery.rb:51:in `from_file'
           /tmp/kitchen/cache/cookbooks/foreflight_nginx/recipes/proxy.rb:7:in `from_file'
         
         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/foreflight_server/libraries/helpers.rb:
         
           1:  def decrypt(encrypted_data_key, key_type)
           2>>   require 'aws-sdk'
           3:  
           4:    encrypted_data_key_binary = Base64.strict_decode64(encrypted_data_key)
           5:    kms_client = Aws::KMS::Client.new(region: 'us-east-1')
           6:  
           7:    data_key_decrypt_response = kms_client.decrypt(
           8:      ciphertext_blob: encrypted_data_key_binary,
           9:      encryption_context: {
          10:        KeyType: key_type
          11:      })
         
         Platform:
         ---------
         x86_64-linux
```

## Kitchen Diagnose

Please include the output of `kitchen diagnose --all` or `kitchen diagnose --loader` (if the first failed).  This can be helpful in troubleshooting, so please include it in a gist.

https://gist.github.com/danieljimenez/295d6c95a0686cd81d5fc8b46b2c9220

**Comment by danieljimenez** [comment] 2017-03-07 04:26
Hi, I'm moving away from using `chef_gem` as the Chef documentation suggests and I ran into this. Am I doing things incorrectly?

**Comment by cheeseplus** [comment] 2017-03-07 13:43
I'm not sure if this has anything to do with kitchen itself. Do you have the complete log to show that it is or isn't installing the gem from metadata? I also notice Ruby 2.1.1 which isn't a Ruby we ship so there might be other things going on with the setup, either way it's probably not related to kitchen itself.

**Comment by danieljimenez** [comment] 2017-03-07 16:27
I agree, I'm not sure it's related to kitchen... but I didn't know where else to raise the flag. About ruby, I can see what I can do to change versions.

So normally when I run chef-client on a server, I get the following output in my log:

```
Installing Cookbook Gems:
  - rsyslog (5.1.0)
  - compat_resource (12.16.3)
  - line (0.6.3)
  - nginx (2.7.6)
  - bluepill (2.4.2)
  - runit (1.7.6)
  - packagecloud (0.2.0)
  - foreflight_nginx (2.2.0)
Compiling Cookbooks...
```

However, when I run my cookbook through test kitchen, I get:

```
Installing Cookbook Gems:
Compiling Cookbooks...
```

... as if it doesn't attempt to install. My kitchen file uses omnibus, so it's always grabbing the latest version of chef.

Chef added support for specifying gems in the metadata file in Chef 12.8, to help facilitate the move away from using chef_gem at compile time.

**Comment by thommay** [comment] 2017-03-07 16:33
Can you provide the full output of `kitchen converge`, please. Also, is this specific to the  `aws_sdk` gem, or is it any gem you try and use in kitchen?

**Comment by danieljimenez** [comment] 2017-03-07 19:39
@thommay Sure, I'll do that in a moment. It's not specific to any gem. I also tried 'gibberish', a gem for encryption.

**Comment by danieljimenez** [comment] 2017-03-08 18:35
Hi, I went a step further and made an example cookbook that fails: 

https://github.com/danieljimenez/example-cookbook

**Comment by danieljimenez** [comment] 2017-03-08 18:36
Log output: https://gist.github.com/danieljimenez/c3a46099cc96f036b778522de548bd3e

**Comment by drrk** [comment] 2017-03-20 08:48
I suspect this is because Berkshelf converts the metadata.rb into a metadata.json before uploading to the test instance, I am not certain but I know that is the behaviour with berks package, so it is worth checking.  If you kitchen login and look at the local cache of cookbooks in /tmp that will show you if I am correct.

**Comment by cheeseplus** [comment] 2017-07-25 19:46
Confirmed this is in fact the metadata.json generation issue, from the node with the test cookbook above:

```
....
  "ohai_versions": [

  ],
  "gems": [

  ]
}
```

Will move this over to berkshelf repo.

**Comment by cheeseplus** [comment] 2017-07-25 19:55
The test cookbook linked doesn't have any gem declarations _in_ metadata.rb and as such isn't a terribly valid test - adding gems to the metadata.rb as per the original report I cannot reproduce the issue with the test cookbook in Chef 12 or 13. So this might have been a bug but it is not one any longer so far as I can tell or reproduce. Closing.

**Closed by cheeseplus** 2017-07-25 19:55 UTC

**Comment by lamont-granquist** [comment] 2017-07-25 20:15
pretty certain this was a bug in berks that got fixed.

as i'm converting berks to use Chef::Cookbook::Metadata and to remove ridley's separate object model entirely, if this bug isn't already fixed in current berkshelf, it soon will be.
