### ISSUE TITLE
"kitchen list" breaks if suits: & - name: fields are missing

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/test-kitchen#893] opened 2015-12-11 05:49 UTC
Example:
`kitchen list`

Error:

```
>>>>>>
No instances for regex `', try running `kitchen list'
```

.kitchen.yml:

```

---
driver:
  name: vagrant
provisioner:
  name: chef_solo
platforms:
  - name: win2012_chef11_14_2
# suites:
#   - name: default
```

**Comment by cheeseplus** [comment] 2016-04-08 05:29
What is the desired outcome here? Kitchen constructs the list by combining the suite name with the platform name - without a suite kitchen is useless and doesn't do anything.

**Comment by vinyar** [comment] 2016-04-11 01:52
If these fields are required in the .kitchen.yml the error message should be more descriptive.
If they're not required, kitchen should run w/o complaining

**Comment by cheeseplus** [comment] 2016-04-12 12:26
Those fields are definitely required as it's how kitchen contructs the names to be regex'd for the commands. As stated above kitchen (as designed) would be (almost) entirely useless unless a suite is set. In theory we could probably assume "default" as that seems to be convention but I'd rather just require and have a nice error when we parse the yaml.

I'm all for more sensible error messages +1

**Comment by amontalban** [comment] 2016-09-01 15:56
I just hit this bug, with this simple text:

```yaml

**Comment by cheeseplus** [comment] 2016-09-01 16:04
@amontalban that's not really a bug - that's YAML being YAML

**Comment by amontalban** [comment] 2016-09-01 16:09
@cheeseplus well it's a bug because it does not validate that the YAML file is a valid YAML, would be great to have a way to have directions to fix this in the file. Even `kitchen diagnose` failed for me.

**Comment by cheeseplus** [comment] 2016-09-01 16:29
kitchen diagnose fails because it has to layer the suites + platforms so for it to even function it must have valid data - we do presume valid YAML but YAML also expects valid YAML

We can add some logging to improve this I also don't think it's unreasonable to require a valid config especially the config is most often generated for you by kitchen init/chef generate. This is to say it's already on the backlog but a PR would greatly accelerate this as it's not really a high level priority.

**Comment by Napster-tools** [comment] 2017-04-28 06:26
I am also getting this error. anyone fixed it already?

**Comment by coderanger** [comment] 2017-04-28 07:13
@Napster-tools As noted above, this isn't really a bug, you probably just don't have a valid Kitchen configuration.

**Comment by cheeseplus** [comment] 2017-07-31 19:45
Closing this one to stop "plus ones" - either the YAML is invalid (in the case of indent problems or inocomplete) this isn't a bug and these values are presumed and put in all generators.

**Closed by cheeseplus** 2017-07-31 19:45 UTC
Labels: Accepted, Improvement
