### ISSUE TITLE
Running dependent cookbook tests

### ISSUE THREAD

**Issue by arieb** [test-kitchen/test-kitchen#941] opened 2016-02-09 10:01 UTC
Hey,
I'm sorry if this question has already been asked before, but I've searched and didn't find something relevant.

I have 2 cookbooks, lets call them A and B, which have serverspec tests written for them, and are run correctly using test kitchen when converging each cookbook separately.

Now i have cookbook C, that depends and uses both A and B cookbooks. How can i run the tests that are already written in the A and B cookbooks when i converge the C cookbook? i don't want to copy paste the spec files from both cookbooks to the C cookbook..

If this is not possible with test-kitchen, how would you recommend accomplishing this?

**Comment by felix-okta** [comment] 2016-02-16 21:10
related to issue #843.

**Comment by cheeseplus** [comment] 2016-04-08 05:24
Closing this as dupe of https://github.com/test-kitchen/test-kitchen/issues/843 and because the root issue is identified in https://github.com/test-kitchen/test-kitchen/issues/843#issuecomment-144130301

It's a non-trivial implementation to support and it start to violate the premise of clean room testing. 

To your question:

When you test cookbook C, it's tests should be it's own tests because of the very fact you are testing a fundamentally different permutation. A + B is not simply the sum of their tests but the _interaction_ of their tests which is a wholly different state.

Tests for cookbook C should test whatever it's core functionality is and be unique to it regardless of what the dependent cookbook tests are as each cookbook is it's own fundamentally different artifact. You can trust that your tests for each A and B test them sufficiently or if you wanted to be absolutely sure, add similar or the same tests for cookbook C.

**Comment by cheeseplus** [comment] 2017-07-26 00:38
Closing as answered.

**Closed by cheeseplus** 2017-07-26 00:38 UTC
Labels: Question
